"use client";

import { useState, type ReactNode } from "react";
import {
  Calendar,
  DatePicker,
  Field,
  FieldLabel,
  Input,
  Popover,
  PopoverContent,
  PopoverTrigger,
  RadioGroup,
  RadioGroupItem,
} from "@/components/ui";
import { Icon } from "@/components/icon";
import { cn } from "@/lib/utils";
import { formatDate } from "@/lib/utils/format";
import { DUE_TERM_OPTIONS } from "@/features/dashboard/create-invoice/constants";

/**
 * Local YYYY-MM-DD, not `toISOString().slice(0, 10)` — that converts to UTC
 * first, which rolls the date back a day for any IST time before 05:30.
 */
export function toDateKey(date: Date): string {
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${date.getFullYear()}-${month}-${day}`;
}

/** Adds `days` to a YYYY-MM-DD key and returns another YYYY-MM-DD key. */
export function addDaysToDateKey(fromKey: string, days: number): string {
  const date = new Date(`${fromKey}T00:00:00`);
  date.setDate(date.getDate() + days);
  return toDateKey(date);
}

export function dueDateForTerm(issueDate: string, termId: string | null): string {
  if (!termId || termId === "custom") return "";
  const term = DUE_TERM_OPTIONS.find((t) => t.id === termId);
  return term ? addDaysToDateKey(issueDate, term.days) : "";
}

function Chip({
  label,
  children,
  className,
}: {
  label: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          className={cn(
            "flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-[13px] font-medium text-foreground transition-colors hover:bg-muted/80",
            className
          )}
        >
          {label}
          <Icon name="pencil" className="h-3 w-3 text-muted-foreground" />
        </button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-72 p-3">
        {children}
      </PopoverContent>
    </Popover>
  );
}

/**
 * Invoice number.
 *
 * The server generates the number when the draft is first created and marks it
 * `autoGenerated`. Production surfaces that as an auto/manual radio pair, and
 * so does this: switching back to Auto generate restores the server's value
 * rather than leaving whatever was typed.
 */
export function InvoiceNumberChip({
  value,
  isManual,
  serverValue,
  onChange,
  onManualChange,
}: {
  value: string;
  isManual: boolean;
  /** The number the server issued, restored when Auto generate is chosen. */
  serverValue: string;
  onChange: (value: string) => void;
  onManualChange: (isManual: boolean) => void;
}) {
  return (
    <Chip label={value || "Invoice number"}>
      <RadioGroup
        value={isManual ? "manual" : "auto"}
        onValueChange={(next) => {
          const manual = next === "manual";
          onManualChange(manual);
          if (!manual) onChange(serverValue);
        }}
        className="mb-3 flex items-center gap-4"
      >
        <label className="flex cursor-pointer items-center gap-1.5 text-[13px] text-foreground">
          <RadioGroupItem value="auto" id="invoice-number-auto" />
          Auto generate
        </label>
        <label className="flex cursor-pointer items-center gap-1.5 text-[13px] text-foreground">
          <RadioGroupItem value="manual" id="invoice-number-manual" />
          Enter manually
        </label>
      </RadioGroup>

      <Field>
        <FieldLabel htmlFor="invoice-number-input">Invoice number</FieldLabel>
        <Input
          id="invoice-number-input"
          value={value}
          disabled={!isManual}
          placeholder="BHM-INV-25-0003"
          onChange={(e) => onChange(e.target.value)}
          className="font-mono text-[13.5px]"
        />
      </Field>
    </Chip>
  );
}

/**
 * Issue date.
 *
 * Production disallows post-dating it (`disabledDate: current > today`). flux's
 * DatePicker only takes a `min`, so this drops to the Calendar primitive
 * underneath it, where `disabled={{ after: today }}` makes the rule real rather
 * than advisory — a future date cannot be picked at all.
 */
export function IssueDateChip({
  value,
  maxDate,
  onChange,
}: {
  value: string;
  /** Latest selectable day, as a YYYY-MM-DD key. Today, in practice. */
  maxDate: string;
  onChange: (value: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const label = value
    ? formatDate(value, { day: "2-digit", month: "short", year: "numeric" })
    : "Issue date";

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-[13px] font-medium text-foreground transition-colors hover:bg-muted/80"
        >
          {label}
          <Icon name="pencil" className="h-3 w-3 text-muted-foreground" />
        </button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-auto p-2">
        <Calendar
          mode="single"
          selected={value ? new Date(`${value}T00:00:00`) : undefined}
          disabled={{ after: new Date(`${maxDate}T00:00:00`) }}
          onSelect={(date?: Date) => {
            if (!date) return;
            onChange(toDateKey(date));
            setOpen(false);
          }}
        />
      </PopoverContent>
    </Popover>
  );
}

function dueLabel(termId: string | null, dueDate: string): string {
  if (!termId) return "";
  if (termId === "custom") {
    return dueDate
      ? `Due on ${formatDate(dueDate, { day: "2-digit", month: "short", year: "numeric" })}`
      : "";
  }
  const term = DUE_TERM_OPTIONS.find((t) => t.id === termId);
  if (!term) return "";
  if (term.id === "today") return "Due today";
  if (term.id === "tomorrow") return "Due tomorrow";
  return `Due in ${term.days} days`;
}

/**
 * Due date, as a term picker rather than a bare calendar.
 *
 * Only the resolved date reaches the API — there is no field for the term — so
 * a reopened draft falls back to showing the explicit date.
 */
export function DueDateChip({
  termId,
  dueDate,
  minDate,
  onTermChange,
  onCustomDateChange,
}: {
  termId: string | null;
  dueDate: string;
  /** Due date cannot precede the issue date. */
  minDate: string;
  onTermChange: (termId: string) => void;
  onCustomDateChange: (value: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const label = dueLabel(termId, dueDate);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        {label ? (
          <button
            type="button"
            className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-[13px] font-medium text-foreground transition-colors hover:bg-muted/80"
          >
            {label}
            <Icon name="pencil" className="h-3 w-3 text-muted-foreground" />
          </button>
        ) : (
          <button
            type="button"
            className="flex items-center gap-1 text-[13px] font-medium text-primary hover:underline"
          >
            <Icon name="plus" className="h-3.5 w-3.5" />
            Add due date
          </button>
        )}
      </PopoverTrigger>

      <PopoverContent align="start" className="w-60 p-1.5">
        {DUE_TERM_OPTIONS.map((term) => (
          <button
            key={term.id}
            type="button"
            onClick={() => {
              onTermChange(term.id);
              setOpen(false);
            }}
            className="flex w-full items-center justify-between rounded-md px-2.5 py-2 text-left text-[13px] transition-colors hover:bg-muted/60"
          >
            {term.label}
            {term.id === termId && <Icon name="check" className="h-3.5 w-3.5 text-primary" />}
          </button>
        ))}

        <div className="my-1 border-t border-border" />

        {termId === "custom" ? (
          <div className="px-1 py-1">
            <DatePicker
              value={dueDate}
              min={minDate}
              onChange={(value) => {
                onCustomDateChange(value);
                setOpen(false);
              }}
            />
          </div>
        ) : (
          <button
            type="button"
            onClick={() => onTermChange("custom")}
            className="flex w-full items-center justify-between rounded-md px-2.5 py-2 text-left text-[13px] transition-colors hover:bg-muted/60"
          >
            Custom
          </button>
        )}
      </PopoverContent>
    </Popover>
  );
}
