import type { BaseResponse } from "@/types/common";

// ─── Wire types ───────────────────────────────────────────────────────────────
// Copied field-for-field from pg-dashboard/src/features/create-invoice/types.ts.
// Do not "tidy" these: the server round-trips the whole InvoiceData object on
// every save, so a dropped field is a silently lost value.

export interface Address {
  city?: string;
  state?: string;
  country?: string;
  zipcode?: string;
  streetAddress1?: string;
  streetAddress2?: string;
}

export type BillerDetails = {
  gstIn?: string;
  legalName?: string;
  phone?: string;
  email?: string;
} & Address;

export interface LineItem {
  type: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  sac: string;
  hsn: string;
  gstRate: number;
  description: string;
}

export type RecurringType = "EVERY_2_WEEK" | "EVERY_1_MONTH" | "EVERY_2_MONTH" | "EVERY_1_QUARTER";

export interface InvoiceData {
  id: string;
  mid: string;
  type: "DEFAULT" | "RECURRING" | "UPLOADED";
  recurringType: RecurringType;
  recurringStartDate: string;
  clientId: string;
  clientName: string;
  clientBusinessName: string;
  currency: string;
  memo: string;
  invoiceNumber: string;
  status: string;
  invoiceDate: string;
  dueDate: string;
  gid: string;
  totalAmount: number;
  pathToParent: string;
  document: string;
  lineItems: LineItem[];
  billerDetails: BillerDetails;
  accountNo: string;
  autoGenerated: boolean;
  formattedCreationDate: string;
  formattedUpdatedDate: string;
  currentStep: string;
  notes: string;
  lut: string;
  discount: {
    discountName?: string;
    value?: string;
    type?: string;
  };
  tax: {
    taxName?: string;
    value?: string;
  };

  progressPercentage?: string | null;
  paidDate?: string;
  signatureEnabled?: boolean;
  logoEnabled?: boolean;
  zohoInvoiceId?: string | null;
  zohoPaymentId?: string | null;
  zohoInvoiceSyncStatus?: "SUCCESS" | "PENDING" | "FAILED" | null;
  zohoPaymentSyncStatus?: "SUCCESS" | "PENDING" | "FAILED" | null;
  source?: "PAYGLOCAL" | "ZOHO" | null;
  lastSyncedTime?: number | null;
  /** Absent on drafts created before themes existed; treat as the default. */
  themeMetadata?: ThemeMetadata | null;
  /** The template this invoice was built from, if any. */
  templateId?: string | null;
}

export interface LinkedTxnDetails {
  amount: string;
  currency: string;
  customerFullName: string;
  externalStatus: string;
  gid: string;
  creationTime: string;
  merchantId: string;
  partnerCustomerCountry: string;
}

export type InvoiceDetailsResponse = BaseResponse<{
  invoice: InvoiceData;
  invoiceId?: string;
  linkedTransaction?: LinkedTxnDetails;
}>;

export type BillerDetailsResponse = BaseResponse<BillerDetails>;

export interface ClientData {
  id: string;
  name: string;
  businessName: string;
  address: Address;
  shippingAddress: Address | null;
}

export type ClientListResponse = BaseResponse<{ clientList: ClientData[] }>;

export interface AccountData {
  id: string;
  accountId: string | null;
  accountHolderName: string;
  accountNumber: string;
  accountNumberType: string;
  bankName: string;
  bankCountry: string;
  currency: string;
  routingCode: string;
  routingCodeType: string;
  bankAddress: string;
  paymentType: string | null;
  createdAt: string;
  updatedAt: string | null;
}

export type AccountListResponse = BaseResponse<{ suggestedAccounts: AccountData[] }>;

/** Manually added accounts use a different, smaller shape than suggested ones. */
export interface AddedAccountDetails {
  accountHolderName: string;
  accountNumber: string;
  bankName: string;
  ifscCode: string;
  uniqueId: string;
}

export type AddedAccountsResponse = BaseResponse<{ bankDetails: AddedAccountDetails[] }>;

export interface LineItemSuggestion {
  unitPrice: string | null;
  hsn: string | null;
  name: string;
  type: string | null;
}

export type LineItemsResponse = BaseResponse<{ lineItems: LineItemSuggestion[] }>;

export type CurrencyData = {
  bankId: string;
  countryName: string;
  currencyCode: string;
  currencyName: string;
  currencySymbol: string;
  iso2CountryCode: string;
};

export type McaCurrencyListResponse = BaseResponse<{
  global_currency: CurrencyData[];
  local_currency: CurrencyData[];
}>;

export type AssetResponse = BaseResponse<{ fileUrl: string }>;

// ─── Themes ───────────────────────────────────────────────────────────────────

/**
 * An invoice's look, as the server stores it.
 *
 * Three enum NAMES, not three hex values: the renderer owns what "SLATE" is
 * worth, so the invoice records the choice and never the colour. The names come
 * from GET /mca-invoice/themes, which is also where the hexes for the on-screen
 * preview come from.
 *
 * Optional on the wire in both directions — omit it on create and the server
 * defaults to CLASSIC / SLATE / AMBER.
 */
export interface ThemeMetadata {
  theme: string;
  color: string;
  accent: string;
}

/** One named colour, e.g. `{ name: "SLATE", hex: "#475569" }`. */
export interface ThemePaletteOption {
  name: string;
  hex: string;
}

export type InvoiceThemesResponse = BaseResponse<{
  themes: string[];
  colors: ThemePaletteOption[];
  accents: ThemePaletteOption[];
}>;

// ─── Editor state ─────────────────────────────────────────────────────────────
// The flat form the Nova-derived editor binds to. This is deliberately NOT the
// wire shape: it holds strings where the form needs strings, and it is mapped
// to a full InvoiceData document by toInvoicePayload() in helpers.ts on every
// autosave. Keeping the two apart is what lets the UI stay flat while the API
// stays the step-shaped upsert production already exposes.

/**
 * A line item as edited. Amounts stay strings because they come straight out of
 * text inputs and must survive a half-typed "12." without being coerced to 12.
 */
export interface LineItemDraft {
  /** Local key only; the server does not round-trip it. */
  key: string;
  /** Maps to LineItem.description — the primary label shown on the invoice. */
  description: string;
  /** Maps to LineItem.type. Production requires it, so the dialog does too. */
  type: string;
  hsn: string;
  /** Percent as a bare number string, e.g. "18". Maps to LineItem.gstRate. */
  gstRate: string;
  unitPrice: string;
  quantity: string;
  /** Ticked in the line-item dialog: pushes the item into SKU management. */
  saveAsSku?: boolean;
}

export interface InvoiceFormState {
  /** Server-owned once the draft exists; empty until the first save returns. */
  invoiceNumber: string;
  /** Whether the merchant overrode the auto-generated number. */
  /** YYYY-MM-DD. */
  invoiceDate: string;
  /** YYYY-MM-DD, or "" when unset. */
  dueDate: string;
  /** Which due-term chip is selected. Local only: the API stores dueDate. */
  dueTermId: string | null;

  clientId: string;
  currency: string;
  lineItems: LineItemDraft[];

  discountName: string;
  discountValue: string;
  discountType: "percentage" | "fixed";
  taxName: string;
  taxValue: string;

  accountNo: string;

  memo: string;
  notes: string;
  lut: string;

  logoEnabled: boolean;
  signatureEnabled: boolean;

  // Branding is deliberately NOT here. The invoice carries `themeMetadata`, so
  // the editor derives it from the fetched document and holds only the
  // merchant's in-session override — see the branding block in InvoiceEditor.
  // Copying it into this form once, as every other field is, is what made a
  // theme revert when a cached document seeded the editor.

  isRecurring: boolean;
  recurringType: RecurringType | "";
  recurringStartDate: string;

  userCreateConsent: boolean;
}

// ─── Branding styles ──────────────────────────────────────────────────────────

/** Which document layout a branding style renders through. */
export type InvoiceLayoutId =
  | "classic"
  | "minimal-mono"
  | "bold-sidebar"
  | "playful-border"
  | "y2k-bold"
  | "geometric-modern";

/**
 * What this app knows about one of the server's themes.
 *
 * The server sends a bare list of names; everything visual about them lives
 * here, keyed by that name. A theme the server offers but this table does not
 * describe still renders — see `themeFor` — so a backend that adds a seventh
 * does not break the picker.
 */
export interface InvoiceTheme {
  /** The server's enum name, e.g. "BOLD_SIDEBAR". */
  name: string;
  /** What the picker calls it, e.g. "Bold Sidebar". */
  label: string;
  layout: InvoiceLayoutId;
  /** Badged in the picker. */
  isNew?: boolean;
}

// ─── Templates ────────────────────────────────────────────────────────────────

/**
 * What a template actually remembers.
 *
 * Deliberately the *reusable shape* of an invoice and nothing that identifies
 * one: no client, no invoice number, no issue or due date, no consent, no linked
 * transaction. Applying a template must never quietly re-point an invoice at
 * last month's customer, and every excluded field is one a merchant has to
 * decide per invoice anyway.
 *
 * `dueTermId` is the exception that proves the rule: the *offset* ("30 days") is
 * reusable, the resolved date is not, so the term is stored and the date is
 * recomputed from today when the template is applied.
 */
export interface InvoiceTemplateSnapshot {
  currency: string;
  lineItems: LineItemDraft[];
  discountName: string;
  discountValue: string;
  discountType: "percentage" | "fixed";
  taxName: string;
  taxValue: string;
  memo: string;
  notes: string;
  lut: string;
  dueTermId: string | null;
  logoEnabled: boolean;
  signatureEnabled: boolean;
  theme: string;
  color: string;
  accent: string;
  isRecurring: boolean;
  recurringType: RecurringType | "";
  /**
   * Carried, never edited here.
   *
   * The API stores it on a template and the editor has no GST control at all —
   * `generate-invoice` is hard-coded to false, exactly as pg-dashboard's create
   * flow is. Holding it means an update round-trips whatever the template
   * already had instead of overwriting it with a guess.
   */
  isGstInvoice: boolean;
}

/**
 * A line item as the templates API carries it.
 *
 * Two departures from the invoice's own line items, both mandated by the
 * endpoint: amounts are numbers rather than the strings production posts, and
 * there is a `name` alongside `description`. The editor has one label per item,
 * so both fields receive it — see `toTemplateWriteBody`.
 */
export interface TemplateLineItem {
  name: string;
  description: string;
  type: string;
  quantity: number;
  unitPrice: number;
  gstRate: number;
  hsn: string;
}

/** The body POSTed to /templates, and PUT to /templates/{id} unchanged. */
export interface TemplateWriteBody {
  name: string;
  currency: string;
  lineItems: TemplateLineItem[];
  isGstInvoice: boolean;
  themeMetadata: ThemeMetadata;
  discount: {
    discountName?: string;
    value?: string;
    type?: string;
    discountAmount?: string;
  };
  tax: {
    taxName?: string;
    value?: string;
    taxAmount?: string;
  };
  memo: string;
  notes: string;
  lut: string;
  /** Whole days from the issue date. Omitted when the template carries no term. */
  dueTermDays?: number;
  /** The invoice's own recurringType vocabulary. Omitted when not recurring. */
  recurring?: RecurringType;
  logoEnabled: boolean;
  signatureEnabled: boolean;
}

/** A template as the API returns it: the body above plus server-managed fields. */
export type ApiInvoiceTemplate = TemplateWriteBody & {
  templateId: string;
  /** Epoch millis as a string. */
  savedAt: string;
  /** Epoch millis as a string; null until the template has been read once. */
  lastUsedAt: string | null;
};

export type TemplateListResponse = BaseResponse<{ templates: ApiInvoiceTemplate[] }>;

export type TemplateResponse = BaseResponse<{ template: ApiInvoiceTemplate }>;

export type TemplateWriteResponse = BaseResponse<{ templateId: string }>;

/**
 * A template as this feature consumes it: identity, plus the snapshot the editor
 * applies. Mapped from ApiInvoiceTemplate by `fromApiTemplate`.
 */
export interface InvoiceTemplate {
  /** The server's `templateId`. */
  id: string;
  name: string;
  /**
   * The one-liner under the name in the picker, e.g. "3 items · USD · due 30
   * days". Derived by `describeSnapshot`, not stored: the API has no such field,
   * and a description a merchant has to invent is one they leave empty.
   */
  description: string;
  /** Epoch millis as a string, which is how the API sends it. */
  savedAt: string;
  /**
   * Epoch millis as a string; null until the template has been read once.
   *
   * Recency, not frequency: the API records this and bumps it itself when a
   * template is read by id, which is the only reason `markUsed` issues a read.
   * It is also the better signal for a picker — what you used last week is a
   * better guess than what you used most in March.
   */
  lastUsedAt: string | null;
  snapshot: InvoiceTemplateSnapshot;
}

// ─── Client creation ──────────────────────────────────────────────────────────
// Shapes copied from pg-dashboard/src/features/mca-clients/types.ts.
//
// Note on encoding: `address.country` and `address.state` carry the reference
// maps' own keys, not display names of our own — production compares state
// against the literal keys of the stateCodes map ("KARNATAKA", "OTHER COUNTRY")
// and submits whichever key get-country-details is keyed by. These shapes are
// still used by AddAddressDialog; client creation itself now goes through
// client-management's ClientFormModal, as it does in pg-dashboard.

export interface ClientAddress {
  streetAddress1: string;
  streetAddress2: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
}

export interface ClientCreateRequest {
  mid: string;
  gstIn: string;
  businessName: string;
  name: string;
  email: string;
  number: string;
  websiteLink?: string;
  address?: ClientAddress;
  shippingAddress?: ClientAddress;
  notes?: string;
  sameAsBusinessName?: boolean;
}

export type ClientCreateResponse = BaseResponse<{ clientId: string }>;

export type StateCodesResponse = BaseResponse<{ stateCodes: Record<string, string> }>;

export type CountryCodesResponse = BaseResponse<{ countryCodes: Record<string, string> }>;

/**
 * A client as the single-client endpoint returns it. Copied from `Client` in
 * pg-dashboard/src/features/mca-clients/types.ts. The address dialog PUTs this
 * whole object back with only the address replaced, exactly as production does,
 * so every field has to survive the round trip.
 */
export interface Client {
  id: string;
  mid: string;
  businessName: string;
  name: string;
  email: string;
  number: string;
  websiteLink?: string;
  country: string;
  status: string;
  totalInvoiceAmount: number;
  outstandingAmount: number;
  address?: ClientAddress;
  shippingAddress?: ClientAddress;
  formattedCreationDate?: string;
  notes?: string;
  currency?: string;
  createdAt?: string;
  type?: string;
  gstIn?: string;
  tags?: string[];
  source?: "PAYGLOCAL" | "ZOHO";
}

export type ClientQueryResponse = BaseResponse<{ client: Client }>;

/**
 * The body POSTed to /mca-invoice/{mid}/create.
 *
 * Deliberately its own type rather than `Partial<InvoiceData>`, because the
 * request and the response genuinely differ and pretending otherwise needs a
 * cast that hides real mismatches:
 *
 *  - line items go up as strings (production posts its editing rows verbatim)
 *    and come back as numbers;
 *  - `subTotal`, `userCreateConsent` and `userLinkConsent` are request-only —
 *    the server consumes them and they never appear on InvoiceData;
 *  - `discount`/`tax` carry a computed *Amount on the way up only.
 */
export interface LineItemPayload {
  key: string;
  type: string;
  description: string;
  hsn: string;
  gstRate: string;
  unitPrice: string;
  quantity: string;
  totalPrice: string;
  saveAsSku: boolean;
}

export type InvoiceCreatePayload = Omit<Partial<InvoiceData>, "lineItems" | "discount" | "tax"> & {
  lineItems?: LineItemPayload[];
  subTotal?: number;
  discount?: {
    discountName?: string;
    value?: string;
    type?: string;
    discountAmount?: string;
  };
  tax?: {
    taxName?: string;
    value?: string;
    taxAmount?: string;
  };
  userCreateConsent?: boolean;
  userLinkConsent?: boolean;
};
