import type { DisputeRow } from "@/features/dashboard/dispute-management/types";

// TODO(integration): replace with the real chargeback-search endpoint once
// available, see the TODO in types.ts.
//
// A full matrix for reviewing the design: every status and closed outcome a
// stage allows (Dispute -> Pre-arbitration -> Arbitration, per the Disputes
// workflow PDF). Dispute and Pre-arbitration: Action required, Insufficient
// documents, Under review, Won, Lost. Arbitration, the final level: Action
// required, Under review, Won, Lost. An escalation is a new stage starting at
// Action required, not a status of its own.
//
// Per the "Pre-arb and arb" design: a contested loss at Dispute or
// Pre-arbitration escalates to the next stage rather than closing, so those
// stages close as Lost only by Accepted or No response. Arbitration is
// final: Withdrawn (with or without a withdrawal fee) or Lost after contest
// (with or without the arbitration fee). Under review rows cover each place
// the evidence can be: with PayGlocal, approved, with the bank. `stage` keeps the step wording for
// reference; the table shows `disputePhase` as its Stage column.
export const MOCK_DISPUTE_ROWS: DisputeRow[] = [
  // ── Stage: Dispute ─────────────────────────────────────────────────────
  // Action required
  {
    disputeId: "du_dis01",
    txnGid: "gl_o-demo001dineed",
    status: "NEEDS_RESPONSE",
    amount: 12500,
    currency: "INR",
    reason: "Fraudulent",
    customerName: "Aditi Rao",
    email: "aditi.rao@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    paymentInstrument: "CARDS",
    disputedOn: "04/10/2026, 09:00:00",
    respondBy: "11/10/2026, 09:00:00",
    disputePhase: "DISPUTE",
    stage: "Dispute raised",
  },
  // Under review
  {
    disputeId: "du_dis02",
    txnGid: "gl_o-demo002diunde",
    status: "UNDER_REVIEW",
    amount: 340,
    currency: "USD",
    reason: "Product not received",
    customerName: "Marcus Lee",
    email: "marcus.lee@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    paymentInstrument: "CARDS",
    disputedOn: "04/10/2026, 12:07:00",
    disputePhase: "DISPUTE",
    stage: "Evidence submitted to PayGlocal",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
    reviewPhase: "PAYGLOCAL_REVIEW",
  },

  // Under review · with the bank
  {
    disputeId: "du_dis02b",
    txnGid: "gl_o-demo002diundeb",
    status: "UNDER_REVIEW",
    amount: 4210,
    currency: "USD",
    reason: "Product not received",
    customerName: "Rhea Kapoor",
    email: "rhea.kapoor@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    paymentInstrument: "CARDS",
    disputedOn: "04/10/2026, 12:07:00",
    disputePhase: "DISPUTE",
    stage: "Evidence submitted to PayGlocal",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
    reviewPhase: "BANK_REVIEW",
  },

  // Insufficient documents
  {
    disputeId: "du_dis03",
    txnGid: "gl_o-demo003dimore",
    status: "MORE_EVIDENCE_NEEDED",
    amount: 9064,
    currency: "INR",
    reason: "Duplicate charge",
    customerName: "Priya Nair",
    email: "priya.nair@example.com",
    cardBrand: "RUPAY",
    maskedCardNumber: "XXXXXXXXXXXX7719",
    paymentInstrument: "CARDS",
    disputedOn: "04/10/2026, 15:14:00",
    respondBy: "11/10/2026, 15:00:00",
    disputePhase: "DISPUTE",
    stage: "Documents insufficient, re-upload required",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Won · Contested
  {
    disputeId: "du_dis05",
    txnGid: "gl_o-demo005diclea",
    status: "CLEARED",
    resolution: "CONTESTED",
    amount: 2038,
    currency: "INR",
    reason: "Other reason",
    customerName: "Sana Qureshi",
    email: "sana.qureshi@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX2290",
    paymentInstrument: "CARDS",
    disputedOn: "03/10/2026, 12:28:00",
    disputePhase: "DISPUTE",
    stage: "Won after bank review",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Won · Customer dropped
  {
    disputeId: "du_dis06",
    txnGid: "gl_o-demo006diclea",
    status: "CLEARED",
    resolution: "CUSTOMER_DROPPED",
    amount: 780,
    currency: "USD",
    reason: "Fraudulent",
    customerName: "Daniel Osei",
    email: "daniel.osei@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX3382",
    paymentInstrument: "CARDS",
    disputedOn: "03/10/2026, 15:35:00",
    disputePhase: "DISPUTE",
    stage: "Withdrawn by the customer",
  },
  // Lost · Accepted
  {
    disputeId: "du_dis08",
    txnGid: "gl_o-demo008diacce",
    status: "ACCEPTED",
    resolution: "ACCEPTED",
    amount: 410,
    currency: "GBP",
    reason: "Duplicate charge",
    customerName: "Kabir Chawla",
    email: "kabir.chawla@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    paymentInstrument: "CARDS",
    disputedOn: "02/10/2026, 12:49:00",
    disputePhase: "DISPUTE",
    stage: "Accepted and refunded",
  },
  // Lost · No response
  {
    disputeId: "du_dis09",
    txnGid: "gl_o-demo009diexpi",
    status: "EXPIRED",
    resolution: "NO_RESPONSE",
    amount: 2396,
    currency: "INR",
    reason: "Subscription cancelled",
    customerName: "Grace Okafor",
    email: "grace.okafor@example.com",
    cardBrand: "RUPAY",
    maskedCardNumber: "XXXXXXXXXXXX7719",
    paymentInstrument: "CARDS",
    disputedOn: "02/10/2026, 15:56:00",
    disputePhase: "DISPUTE",
    stage: "Auto-closed, no response",
  },
  // ── Stage: Pre-arbitration ─────────────────────────────────────────────
  // Action required
  {
    disputeId: "du_pre10",
    txnGid: "gl_o-demo010prneed",
    status: "NEEDS_RESPONSE",
    amount: 12833,
    currency: "INR",
    reason: "Other reason",
    customerName: "Ishaan Verma",
    email: "ishaan.verma@example.com",
    cardBrand: "AMEX",
    maskedCardNumber: "XXXXXXXXXXXX6603",
    paymentInstrument: "CARDS",
    disputedOn: "01/10/2026, 09:03:00",
    respondBy: "08/10/2026, 09:00:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Dispute raised",
  },
  // Under review
  {
    disputeId: "du_pre11",
    txnGid: "gl_o-demo011prunde",
    status: "UNDER_REVIEW",
    amount: 340,
    currency: "USD",
    reason: "Fraudulent",
    customerName: "Olivia Bennett",
    email: "olivia.bennett@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX2290",
    paymentInstrument: "CARDS",
    disputedOn: "01/10/2026, 12:10:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Evidence submitted to PayGlocal",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
    reviewPhase: "APPROVED",
  },

  // Insufficient documents
  {
    disputeId: "du_pre12",
    txnGid: "gl_o-demo012prmore",
    status: "MORE_EVIDENCE_NEEDED",
    amount: 9397,
    currency: "INR",
    reason: "Product not received",
    customerName: "Rohan Mehta",
    email: "rohan.mehta@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX3382",
    paymentInstrument: "CARDS",
    disputedOn: "01/10/2026, 15:17:00",
    respondBy: "08/10/2026, 15:00:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Documents insufficient, re-upload required",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Won · Contested
  {
    disputeId: "du_pre14",
    txnGid: "gl_o-demo014prclea",
    status: "CLEARED",
    resolution: "CONTESTED",
    amount: 2371,
    currency: "INR",
    reason: "Subscription cancelled",
    customerName: "Yusuf Khan",
    email: "yusuf.khan@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    paymentInstrument: "CARDS",
    disputedOn: "30/09/2026, 12:31:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Won after bank review",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Won · Customer dropped
  {
    disputeId: "du_pre15",
    txnGid: "gl_o-demo015prclea",
    status: "CLEARED",
    resolution: "CUSTOMER_DROPPED",
    amount: 780,
    currency: "USD",
    reason: "Other reason",
    customerName: "Ananya Iyer",
    email: "ananya.iyer@example.com",
    cardBrand: "RUPAY",
    maskedCardNumber: "XXXXXXXXXXXX7719",
    paymentInstrument: "CARDS",
    disputedOn: "30/09/2026, 15:38:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Withdrawn by the customer",
  },
  // Lost · Accepted
  {
    disputeId: "du_pre17",
    txnGid: "gl_o-demo017pracce",
    status: "ACCEPTED",
    resolution: "ACCEPTED",
    amount: 410,
    currency: "GBP",
    reason: "Product not received",
    customerName: "Nora Lindqvist",
    email: "nora.lindqvist@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX2290",
    paymentInstrument: "CARDS",
    disputedOn: "29/09/2026, 12:52:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Accepted and refunded",
  },
  // Lost · No response
  {
    disputeId: "du_pre18",
    txnGid: "gl_o-demo018prexpi",
    status: "EXPIRED",
    resolution: "NO_RESPONSE",
    amount: 2729,
    currency: "INR",
    reason: "Duplicate charge",
    customerName: "Arjun Pillai",
    email: "arjun.pillai@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX3382",
    paymentInstrument: "CARDS",
    disputedOn: "29/09/2026, 15:59:00",
    disputePhase: "PRE_ARBITRATION",
    stage: "Pre-arbitration: Auto-closed, no response",
  },
  // ── Stage: Arbitration ─────────────────────────────────────────────────
  // Action required
  {
    disputeId: "du_arb19",
    txnGid: "gl_o-demo019arneed",
    status: "NEEDS_RESPONSE",
    amount: 13166,
    currency: "INR",
    reason: "Subscription cancelled",
    customerName: "Fatima Zahra",
    email: "fatima.zahra@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    paymentInstrument: "CARDS",
    disputedOn: "05/10/2026, 08:30:00",
    respondBy: "06/10/2026, 08:30:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Dispute raised",
    withdrawalFeeApplies: true,
  },

  // Action required · no withdrawal fee
  {
    disputeId: "du_arb19b",
    txnGid: "gl_o-demo019arneedb",
    status: "NEEDS_RESPONSE",
    amount: 7420,
    currency: "INR",
    reason: "Subscription cancelled",
    customerName: "Nikhil Rao",
    email: "nikhil.rao@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    paymentInstrument: "CARDS",
    disputedOn: "05/10/2026, 08:30:00",
    respondBy: "06/10/2026, 08:30:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Dispute raised",
  },
  // Under review
  {
    disputeId: "du_arb20",
    txnGid: "gl_o-demo020arunde",
    status: "UNDER_REVIEW",
    amount: 340,
    currency: "USD",
    reason: "Other reason",
    customerName: "Vikram Joshi",
    email: "vikram.joshi@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    paymentInstrument: "CARDS",
    disputedOn: "28/09/2026, 12:13:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Evidence submitted to PayGlocal",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
    reviewPhase: "BANK_REVIEW",
  },

  // Won · Contested
  {
    disputeId: "du_arb22",
    txnGid: "gl_o-demo022arclea",
    status: "CLEARED",
    resolution: "CONTESTED",
    amount: 320,
    currency: "EUR",
    reason: "Product not received",
    customerName: "Neha Kulkarni",
    email: "neha.kulkarni@example.com",
    cardBrand: "AMEX",
    maskedCardNumber: "XXXXXXXXXXXX6603",
    paymentInstrument: "CARDS",
    disputedOn: "27/09/2026, 09:27:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Won after bank review",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Won · Customer dropped
  {
    disputeId: "du_arb23",
    txnGid: "gl_o-demo023arclea",
    status: "CLEARED",
    resolution: "CUSTOMER_DROPPED",
    amount: 2704,
    currency: "INR",
    reason: "Duplicate charge",
    customerName: "Samuel Adeyemi",
    email: "samuel.adeyemi@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX2290",
    paymentInstrument: "CARDS",
    disputedOn: "27/09/2026, 12:34:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Withdrawn by the customer",
  },
  // Lost · Contested
  {
    disputeId: "du_arb24",
    txnGid: "gl_o-demo024archar",
    status: "CHARGED_BACK",
    resolution: "CONTESTED",
    amount: 780,
    currency: "USD",
    reason: "Subscription cancelled",
    customerName: "Riya Sen",
    email: "riya.sen@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX3382",
    paymentInstrument: "CARDS",
    disputedOn: "27/09/2026, 15:41:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Lost after bank review",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
    appliedFee: { kind: "ARBITRATION", amount: 800, currency: "USD" },
  },

  // Lost · Contested · no arbitration fee
  {
    disputeId: "du_arb24b",
    txnGid: "gl_o-demo024archarb",
    status: "CHARGED_BACK",
    resolution: "CONTESTED",
    amount: 3650,
    currency: "USD",
    reason: "Subscription cancelled",
    customerName: "Emma Brooks",
    email: "emma.brooks@example.com",
    cardBrand: "MASTERCARD",
    maskedCardNumber: "XXXXXXXXXXXX3382",
    paymentInstrument: "CARDS",
    disputedOn: "27/09/2026, 15:41:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Lost after bank review",
    documents: ["invoice.pdf", "proof_of_delivery.jpg"],
  },
  // Lost · Withdrawn · withdrawal fee
  {
    disputeId: "du_arb25",
    txnGid: "gl_o-demo025aracce",
    status: "ACCEPTED",
    resolution: "WITHDRAWN",
    amount: 6488,
    currency: "INR",
    reason: "Other reason",
    customerName: "Hiro Tanaka",
    email: "hiro.tanaka@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    paymentInstrument: "CARDS",
    disputedOn: "26/09/2026, 09:48:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Accepted and refunded",
    appliedFee: { kind: "WITHDRAWAL", amount: 200, currency: "USD" },
  },

  // Lost · Withdrawn · no withdrawal fee
  {
    disputeId: "du_arb25b",
    txnGid: "gl_o-demo025aracceb",
    status: "ACCEPTED",
    resolution: "WITHDRAWN",
    amount: 2780,
    currency: "INR",
    reason: "Other reason",
    customerName: "Lucas Moreau",
    email: "lucas.moreau@example.com",
    cardBrand: "VISA",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    paymentInstrument: "CARDS",
    disputedOn: "26/09/2026, 09:48:00",
    disputePhase: "ARBITRATION",
    stage: "Arbitration: Accepted and refunded",
  },
];
