import { forwardRef, type SVGProps } from "react";
/** AU Small Finance Bank Limited: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const AublBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    id="bank-aubl-Layer_1"
    x={0}
    y={0}
    viewBox="0 0 87 87"
    width="1em"
    height="1em"
    role="img"
    aria-label="AU Small Finance Bank Limited"
    ref={ref}
    {...props}
  >
    <style id="style9" type="text/css">
      {".bank-aubl-st0{fill:#612e87}.bank-aubl-st1{fill:#ef6719}"}
    </style>
    <g id="bank-aubl-g228" transform="translate(.8 .8)">
      <path
        id="bank-aubl-path13"
        d="M42.7 0C19.1 0 0 19.1 0 42.7s19.1 42.7 42.7 42.7 42.7-19.1 42.7-42.7C85.5 19.1 66.3 0 42.7 0"
        className="bank-aubl-st1"
      />
      <path
        id="bank-aubl-path15"
        d="M38.3 58.2c-1.6 0-3-1-3.5-2.5l-2.2-5.1H18.4l-2.3 5.3c-.5 1.4-1.9 2.2-3.3 2.2-1.8 0-3.3-1.5-3.3-3.3v-.1c0-.5.2-1 .4-1.5l11.3-25.5c.7-1.7 2.3-2.9 4.2-2.8h.4c1.8 0 3.5 1.1 4.1 2.8l11.3 25.5c.9 1.6.2 3.6-1.4 4.5-.5.4-1 .5-1.5.5"
        className="bank-aubl-st0"
      />
      <path
        id="bank-aubl-polygon17"
        d="m108.2 112.3-4.5-10.7-4.5 10.7z"
        className="bank-aubl-st1"
        transform="translate(-78.2 -67.9)"
      />
      <path
        id="bank-aubl-path19"
        d="M72.4 43.8c0 9.8-5.5 14.6-14.2 14.6s-14-4.9-14-14.4V28.8c-.1-2 1.4-3.6 3.4-3.8 2-.1 3.6 1.4 3.8 3.4v15.4c0 5.3 2.6 8 7 8s7-2.6 7-7.8V28.8c-.1-2 1.4-3.6 3.4-3.8 2-.1 3.6 1.4 3.8 3.4v.4z"
        className="bank-aubl-st0"
      />
    </g>
  </svg>
));
AublBankLogo.displayName = "AublBankLogo";
