import { forwardRef, type SVGProps } from "react";
/** CSB Bank Limited: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const CsbkBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    id="bank-csbk-Layer_1"
    data-name="Layer 1"
    viewBox="0 0 94.008 86.05"
    width="1em"
    height="1em"
    role="img"
    aria-label="CSB Bank Limited"
    ref={ref}
    {...props}
  >
    <defs id="bank-csbk-defs1546">
      <style id="style1544">{".bank-csbk-cls-2{fill:#f37024}"}</style>
    </defs>
    <path
      id="bank-csbk-path1552"
      d="M45.22 35.73a25.14 25.14 0 0 0-20.83 11.06 18.85 18.85 0 1 1 0 28.2 25.16 25.16 0 1 0 20.83-39.26"
      className="bank-csbk-cls-2"
    />
    <path
      id="bank-csbk-path1554"
      d="M48.01 11.09a25.16 25.16 0 0 0-2.51 23.44 18.88 18.88 0 1 1 23.34 15.79 25.16 25.16 0 1 0-20.83-39.26"
      className="bank-csbk-cls-2"
    />
    <path
      id="bank-csbk-path1556"
      d="M31.28 69.32a25.1 25.1 0 0 0 17.5-15.8 18.86 18.86 0 1 1-6.85-27.36 25.16 25.16 0 1 0-10.65 43.16"
      className="bank-csbk-cls-2"
    />
  </svg>
));
CsbkBankLogo.displayName = "CsbkBankLogo";
