import { forwardRef, type SVGProps } from "react";
/** HDFC Bank: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const HdfcBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 47.853 47.853"
    width="1em"
    height="1em"
    role="img"
    aria-label="HDFC Bank"
    ref={ref}
    {...props}
  >
    <path
      d="M0 0h47.853v47.853H0Z"
      style={{
        fill: "#ed232a",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 6.01697,
      }}
    />
    <path
      d="M8.376 8.376h31.107v31.107H8.376Z"
      style={{
        fill: "#fff",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 6.01697,
      }}
    />
    <path
      d="M21.535 0h4.783v47.853h-4.783z"
      style={{
        fill: "#fff",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 6.01697,
      }}
    />
    <path
      d="M0 21.54h47.853v4.784H0Z"
      style={{
        fill: "#fff",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 6.01697,
      }}
    />
    <path
      d="M16.751 16.751h14.357v14.357H16.75Z"
      style={{
        fill: "#004c8f",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 6.01697,
      }}
    />
  </svg>
));
HdfcBankLogo.displayName = "HdfcBankLogo";
