import { forwardRef, type SVGProps } from "react";
/** IDFC First Bank Limited: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const IdfbBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 64.027 64.027"
    width="1em"
    height="1em"
    role="img"
    aria-label="IDFC First Bank Limited"
    ref={ref}
    {...props}
  >
    <g fill="none" fillRule="evenodd">
      <path
        fill="#9d1d27"
        d="M9.535 73.513h64.027V9.487H9.535Z"
        style={{
          strokeWidth: 0.458447,
        }}
        transform="translate(-9.535 -9.487)"
      />
      <path fill="#fefefe" d="M8.43 8.476H55.5v47.077H8.43V8.477Zm51.035-3.96-55-.003v55h55z" />
      <path fill="#fefefe" d="M13.465 22.513h37v-9h-37Zm0 28h9v-9h-9Zm0-14h23v-9h-23Z" />
    </g>
  </svg>
));
IdfbBankLogo.displayName = "IdfbBankLogo";
