"use client";

import { lazy, type SVGProps } from "react";

/**
 * The bank logos in this folder, by IFSC prefix (the first four letters of
 * a branch's IFSC code), with each bank's name. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file.
 *
 * Each logo is its own lazy component, so a page downloads only the banks it
 * shows (see BankLogo in @/components/common/BankLogo). Render one with
 * <LazyBankLogo slug="hdfc" /> inside a Suspense boundary.
 */
export interface BankLogoEntry {
  slug: string;
  name: string;
}

export const BANK_LOGOS: BankLogoEntry[] = [
  { slug: "airp", name: "Airtel Payments Bank" },
  { slug: "aubl", name: "AU Small Finance Bank Limited" },
  { slug: "barb", name: "Bank of Baroda" },
  { slug: "bdbl", name: "Bandhan Bank" },
  { slug: "bkid", name: "Bank of India" },
  { slug: "cbin", name: "Central Bank of India" },
  { slug: "ciub", name: "City Union Bank" },
  { slug: "cnrb", name: "Canara Bank" },
  { slug: "csbk", name: "CSB Bank Limited" },
  { slug: "dcbl", name: "DCB Bank Limited" },
  { slug: "dlxb", name: "Dhanalakshmi Bank" },
  { slug: "esmf", name: "ESAF Small Finance Bank" },
  { slug: "fdrl", name: "Federal Bank" },
  { slug: "fino", name: "FINO Payments Bank" },
  { slug: "hdfc", name: "HDFC Bank" },
  { slug: "ibkl", name: "IDBI Bank" },
  { slug: "icic", name: "ICICI Bank Limited" },
  { slug: "idfb", name: "IDFC First Bank Limited" },
  { slug: "idib", name: "Indian Bank" },
  { slug: "indb", name: "IndusInd Bank" },
  { slug: "ioba", name: "Indian Overseas Bank" },
  { slug: "jaka", name: "Jammu and Kashmir Bank" },
  { slug: "jiop", name: "Jio Payments Bank" },
  { slug: "karb", name: "Karnataka Bank Limited" },
  { slug: "kkbk", name: "Kotak Mahindra Bank Limited" },
  { slug: "kvbl", name: "Karur Vysya Bank" },
  { slug: "mahb", name: "Bank of Maharashtra" },
  { slug: "ntbl", name: "The Nainital Bank Limited" },
  { slug: "psib", name: "Punjab and Sind Bank" },
  { slug: "punb", name: "Punjab National Bank" },
  { slug: "pytm", name: "Paytm Payments Bank" },
  { slug: "ratn", name: "RBL Bank Limited" },
  { slug: "sbin", name: "State Bank of India" },
  { slug: "scbl", name: "Standard Chartered Bank" },
  { slug: "sibl", name: "South Indian Bank" },
  { slug: "tmbl", name: "Tamilnad Mercantile Bank Limited" },
  { slug: "ubin", name: "Union Bank of India" },
  { slug: "ucba", name: "UCO Bank" },
  { slug: "ujvn", name: "Ujjivan Small Finance Bank Ltd" },
  { slug: "utib", name: "Axis Bank" },
  { slug: "yesb", name: "Yes Bank" },
];

const AirpBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/AirpBankLogo").then((m) => ({ default: m.AirpBankLogo }))
);
const AublBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/AublBankLogo").then((m) => ({ default: m.AublBankLogo }))
);
const BarbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/BarbBankLogo").then((m) => ({ default: m.BarbBankLogo }))
);
const BdblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/BdblBankLogo").then((m) => ({ default: m.BdblBankLogo }))
);
const BkidBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/BkidBankLogo").then((m) => ({ default: m.BkidBankLogo }))
);
const CbinBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/CbinBankLogo").then((m) => ({ default: m.CbinBankLogo }))
);
const CiubBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/CiubBankLogo").then((m) => ({ default: m.CiubBankLogo }))
);
const CnrbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/CnrbBankLogo").then((m) => ({ default: m.CnrbBankLogo }))
);
const CsbkBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/CsbkBankLogo").then((m) => ({ default: m.CsbkBankLogo }))
);
const DcblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/DcblBankLogo").then((m) => ({ default: m.DcblBankLogo }))
);
const DlxbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/DlxbBankLogo").then((m) => ({ default: m.DlxbBankLogo }))
);
const EsmfBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/EsmfBankLogo").then((m) => ({ default: m.EsmfBankLogo }))
);
const FdrlBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/FdrlBankLogo").then((m) => ({ default: m.FdrlBankLogo }))
);
const FinoBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/FinoBankLogo").then((m) => ({ default: m.FinoBankLogo }))
);
const HdfcBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/HdfcBankLogo").then((m) => ({ default: m.HdfcBankLogo }))
);
const IbklBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IbklBankLogo").then((m) => ({ default: m.IbklBankLogo }))
);
const IcicBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IcicBankLogo").then((m) => ({ default: m.IcicBankLogo }))
);
const IdfbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IdfbBankLogo").then((m) => ({ default: m.IdfbBankLogo }))
);
const IdibBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IdibBankLogo").then((m) => ({ default: m.IdibBankLogo }))
);
const IndbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IndbBankLogo").then((m) => ({ default: m.IndbBankLogo }))
);
const IobaBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/IobaBankLogo").then((m) => ({ default: m.IobaBankLogo }))
);
const JakaBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/JakaBankLogo").then((m) => ({ default: m.JakaBankLogo }))
);
const JiopBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/JiopBankLogo").then((m) => ({ default: m.JiopBankLogo }))
);
const KarbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/KarbBankLogo").then((m) => ({ default: m.KarbBankLogo }))
);
const KkbkBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/KkbkBankLogo").then((m) => ({ default: m.KkbkBankLogo }))
);
const KvblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/KvblBankLogo").then((m) => ({ default: m.KvblBankLogo }))
);
const MahbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/MahbBankLogo").then((m) => ({ default: m.MahbBankLogo }))
);
const NtblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/NtblBankLogo").then((m) => ({ default: m.NtblBankLogo }))
);
const PsibBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/PsibBankLogo").then((m) => ({ default: m.PsibBankLogo }))
);
const PunbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/PunbBankLogo").then((m) => ({ default: m.PunbBankLogo }))
);
const PytmBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/PytmBankLogo").then((m) => ({ default: m.PytmBankLogo }))
);
const RatnBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/RatnBankLogo").then((m) => ({ default: m.RatnBankLogo }))
);
const SbinBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/SbinBankLogo").then((m) => ({ default: m.SbinBankLogo }))
);
const ScblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/ScblBankLogo").then((m) => ({ default: m.ScblBankLogo }))
);
const SiblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/SiblBankLogo").then((m) => ({ default: m.SiblBankLogo }))
);
const TmblBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/TmblBankLogo").then((m) => ({ default: m.TmblBankLogo }))
);
const UbinBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/UbinBankLogo").then((m) => ({ default: m.UbinBankLogo }))
);
const UcbaBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/UcbaBankLogo").then((m) => ({ default: m.UcbaBankLogo }))
);
const UjvnBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/UjvnBankLogo").then((m) => ({ default: m.UjvnBankLogo }))
);
const UtibBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/UtibBankLogo").then((m) => ({ default: m.UtibBankLogo }))
);
const YesbBankLogoLazy = lazy(() =>
  import("@/components/icon/banks/YesbBankLogo").then((m) => ({ default: m.YesbBankLogo }))
);

export function LazyBankLogo({ slug, ...props }: { slug: string } & SVGProps<SVGSVGElement>) {
  switch (slug) {
    case "airp":
      return <AirpBankLogoLazy {...props} />;
    case "aubl":
      return <AublBankLogoLazy {...props} />;
    case "barb":
      return <BarbBankLogoLazy {...props} />;
    case "bdbl":
      return <BdblBankLogoLazy {...props} />;
    case "bkid":
      return <BkidBankLogoLazy {...props} />;
    case "cbin":
      return <CbinBankLogoLazy {...props} />;
    case "ciub":
      return <CiubBankLogoLazy {...props} />;
    case "cnrb":
      return <CnrbBankLogoLazy {...props} />;
    case "csbk":
      return <CsbkBankLogoLazy {...props} />;
    case "dcbl":
      return <DcblBankLogoLazy {...props} />;
    case "dlxb":
      return <DlxbBankLogoLazy {...props} />;
    case "esmf":
      return <EsmfBankLogoLazy {...props} />;
    case "fdrl":
      return <FdrlBankLogoLazy {...props} />;
    case "fino":
      return <FinoBankLogoLazy {...props} />;
    case "hdfc":
      return <HdfcBankLogoLazy {...props} />;
    case "ibkl":
      return <IbklBankLogoLazy {...props} />;
    case "icic":
      return <IcicBankLogoLazy {...props} />;
    case "idfb":
      return <IdfbBankLogoLazy {...props} />;
    case "idib":
      return <IdibBankLogoLazy {...props} />;
    case "indb":
      return <IndbBankLogoLazy {...props} />;
    case "ioba":
      return <IobaBankLogoLazy {...props} />;
    case "jaka":
      return <JakaBankLogoLazy {...props} />;
    case "jiop":
      return <JiopBankLogoLazy {...props} />;
    case "karb":
      return <KarbBankLogoLazy {...props} />;
    case "kkbk":
      return <KkbkBankLogoLazy {...props} />;
    case "kvbl":
      return <KvblBankLogoLazy {...props} />;
    case "mahb":
      return <MahbBankLogoLazy {...props} />;
    case "ntbl":
      return <NtblBankLogoLazy {...props} />;
    case "psib":
      return <PsibBankLogoLazy {...props} />;
    case "punb":
      return <PunbBankLogoLazy {...props} />;
    case "pytm":
      return <PytmBankLogoLazy {...props} />;
    case "ratn":
      return <RatnBankLogoLazy {...props} />;
    case "sbin":
      return <SbinBankLogoLazy {...props} />;
    case "scbl":
      return <ScblBankLogoLazy {...props} />;
    case "sibl":
      return <SiblBankLogoLazy {...props} />;
    case "tmbl":
      return <TmblBankLogoLazy {...props} />;
    case "ubin":
      return <UbinBankLogoLazy {...props} />;
    case "ucba":
      return <UcbaBankLogoLazy {...props} />;
    case "ujvn":
      return <UjvnBankLogoLazy {...props} />;
    case "utib":
      return <UtibBankLogoLazy {...props} />;
    case "yesb":
      return <YesbBankLogoLazy {...props} />;
    default:
      return null;
  }
}
