import { forwardRef, type SVGProps } from "react";
/** RBL Bank Limited: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const RatnBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    xmlSpace="preserve"
    viewBox="0 0 57.732 75.775"
    width="1em"
    height="1em"
    role="img"
    aria-label="RBL Bank Limited"
    ref={ref}
    {...props}
  >
    <defs>
      <clipPath id="bank-ratn-a" clipPathUnits="userSpaceOnUse">
        <path d="M612.394 61.032h48.123v.003h-48.123z" />
      </clipPath>
      <clipPath id="bank-ratn-b" clipPathUnits="userSpaceOnUse">
        <path d="M564.445 61.032h48.124v.003h-48.124z" />
      </clipPath>
      <clipPath id="bank-ratn-c" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-d" clipPathUnits="userSpaceOnUse">
        <path d="M1227.427 523.879h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-e" clipPathUnits="userSpaceOnUse">
        <path d="M1227.338 523.956h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-f" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-g" clipPathUnits="userSpaceOnUse">
        <path d="M1229.225 523.879h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-h" clipPathUnits="userSpaceOnUse">
        <path d="M1229.138 523.956h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-i" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-j" clipPathUnits="userSpaceOnUse">
        <path d="M1234.085 523.879h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-k" clipPathUnits="userSpaceOnUse">
        <path d="M1234.058 523.956h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-l" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-m" clipPathUnits="userSpaceOnUse">
        <path d="M1224.907 524.057h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-n" clipPathUnits="userSpaceOnUse">
        <path d="M1224.818 524.075h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-o" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-p" clipPathUnits="userSpaceOnUse">
        <path d="M1234.626 524.057h.777v-.235h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-q" clipPathUnits="userSpaceOnUse">
        <path d="M1234.538 524.075h.984v-.384h-.984z" />
      </clipPath>
      <clipPath id="bank-ratn-r" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-s" clipPathUnits="userSpaceOnUse">
        <path d="M1229.766 524.235h.777V524h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-t" clipPathUnits="userSpaceOnUse">
        <path d="M1229.738 524.315h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-u" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-v" clipPathUnits="userSpaceOnUse">
        <path d="M1232.825 524.235h.777V524h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-w" clipPathUnits="userSpaceOnUse">
        <path d="M1232.738 524.315h.984v-.384h-.984z" />
      </clipPath>
      <clipPath id="bank-ratn-x" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-y" clipPathUnits="userSpaceOnUse">
        <path d="M1236.604 524.414h1.076v-.235h-1.076z" />
      </clipPath>
      <clipPath id="bank-ratn-z" clipPathUnits="userSpaceOnUse">
        <path d="M1236.578 524.435h1.224v-.384h-1.224z" />
      </clipPath>
      <clipPath id="bank-ratn-A" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-B" clipPathUnits="userSpaceOnUse">
        <path d="M1236.604 524.592h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-C" clipPathUnits="userSpaceOnUse">
        <path d="M1236.578 524.675h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-D" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-E" clipPathUnits="userSpaceOnUse">
        <path d="M1234.085 538.144h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-F" clipPathUnits="userSpaceOnUse">
        <path d="M1234.058 538.235h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-G" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-H" clipPathUnits="userSpaceOnUse">
        <path d="M1235.886 538.144h1.795v-.235h-1.795z" />
      </clipPath>
      <clipPath id="bank-ratn-I" clipPathUnits="userSpaceOnUse">
        <path d="M1235.858 538.235h1.944v-.384h-1.944z" />
      </clipPath>
      <clipPath id="bank-ratn-J" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-K" clipPathUnits="userSpaceOnUse">
        <path d="M1231.026 538.323h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-L" clipPathUnits="userSpaceOnUse">
        <path d="M1230.938 538.355h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-M" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-N" clipPathUnits="userSpaceOnUse">
        <path d="M1226.706 538.501h1.857v-.235h-1.857z" />
      </clipPath>
      <clipPath id="bank-ratn-O" clipPathUnits="userSpaceOnUse">
        <path d="M1226.618 538.595h2.064v-.384h-2.064z" />
      </clipPath>
      <clipPath id="bank-ratn-P" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-Q" clipPathUnits="userSpaceOnUse">
        <path d="M1229.766 538.501h.777v-.235h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-R" clipPathUnits="userSpaceOnUse">
        <path d="M1229.738 538.595h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-S" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-T" clipPathUnits="userSpaceOnUse">
        <path d="M1231.565 538.501h.777v-.235h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-U" clipPathUnits="userSpaceOnUse">
        <path d="M1231.538 538.595h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-V" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-W" clipPathUnits="userSpaceOnUse">
        <path d="M1233.546 538.501h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-X" clipPathUnits="userSpaceOnUse">
        <path d="M1233.458 538.595h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-Y" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-Z" clipPathUnits="userSpaceOnUse">
        <path d="M1225.181 233.343h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-aa" clipPathUnits="userSpaceOnUse">
        <path d="M1225.058 233.435h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-ab" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-ac" clipPathUnits="userSpaceOnUse">
        <path d="M1227.52 233.343h.777v-.236h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-ad" clipPathUnits="userSpaceOnUse">
        <path d="M1227.458 233.435h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-ae" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-af" clipPathUnits="userSpaceOnUse">
        <path d="M1229.319 233.521h.777v-.235h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-ag" clipPathUnits="userSpaceOnUse">
        <path d="M1229.258 233.555h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-ah" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-ai" clipPathUnits="userSpaceOnUse">
        <path d="M1226.979 233.701h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-aj" clipPathUnits="userSpaceOnUse">
        <path d="M1226.858 233.795h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-ak" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-al" clipPathUnits="userSpaceOnUse">
        <path d="M1229.319 233.701h2.037v-.235h-2.037z" />
      </clipPath>
      <clipPath id="bank-ratn-am" clipPathUnits="userSpaceOnUse">
        <path d="M1229.258 233.795h2.184v-.384h-2.184z" />
      </clipPath>
      <clipPath id="bank-ratn-an" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-ao" clipPathUnits="userSpaceOnUse">
        <path d="M1233.64 233.701h4.041v-.235h-4.041z" />
      </clipPath>
      <clipPath id="bank-ratn-ap" clipPathUnits="userSpaceOnUse">
        <path d="M1233.578 233.795h4.224v-.384h-4.224z" />
      </clipPath>
      <clipPath id="bank-ratn-aq" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-ar" clipPathUnits="userSpaceOnUse">
        <path d="M1234.179 233.878h.777v-.236h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-as" clipPathUnits="userSpaceOnUse">
        <path d="M1234.058 233.915h.984v-.384h-.984z" />
      </clipPath>
      <clipPath id="bank-ratn-at" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-au" clipPathUnits="userSpaceOnUse">
        <path d="M1231.839 234.056h5.841v-.235h-5.841z" />
      </clipPath>
      <clipPath id="bank-ratn-av" clipPathUnits="userSpaceOnUse">
        <path d="M1231.778 234.155h6.024v-.384h-6.024z" />
      </clipPath>
      <clipPath id="bank-ratn-aw" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-ax" clipPathUnits="userSpaceOnUse">
        <path d="M1236.698 234.234h.982v-.235h-.982z" />
      </clipPath>
      <clipPath id="bank-ratn-ay" clipPathUnits="userSpaceOnUse">
        <path d="M1236.578 234.275h1.224v-.384h-1.224z" />
      </clipPath>
      <clipPath id="bank-ratn-az" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aA" clipPathUnits="userSpaceOnUse">
        <path d="M1236.159 245.112h.597v-.414h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-aB" clipPathUnits="userSpaceOnUse">
        <path d="M1236.098 245.195h.744v-.624h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-aC" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aD" clipPathUnits="userSpaceOnUse">
        <path d="M1228.239 245.111h1.137v-.235h-1.137z" />
      </clipPath>
      <clipPath id="bank-ratn-aE" clipPathUnits="userSpaceOnUse">
        <path d="M1228.178 245.195h1.224v-.384h-1.224z" />
      </clipPath>
      <clipPath id="bank-ratn-aF" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aG" clipPathUnits="userSpaceOnUse">
        <path d="M1230.579 245.111h3.657v-.235h-3.657z" />
      </clipPath>
      <clipPath id="bank-ratn-aH" clipPathUnits="userSpaceOnUse">
        <path d="M1230.458 245.195h3.864v-.384h-3.864z" />
      </clipPath>
      <clipPath id="bank-ratn-aI" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aJ" clipPathUnits="userSpaceOnUse">
        <path d="M1235.438 245.29h.777v-.235h-.777z" />
      </clipPath>
      <clipPath id="bank-ratn-aK" clipPathUnits="userSpaceOnUse">
        <path d="M1235.378 245.315h.864v-.384h-.864z" />
      </clipPath>
      <clipPath id="bank-ratn-aL" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aM" clipPathUnits="userSpaceOnUse">
        <path d="M1228.78 245.469h.597v-.236h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-aN" clipPathUnits="userSpaceOnUse">
        <path d="M1228.658 245.555h.744v-.384h-.744z" />
      </clipPath>
      <clipPath id="bank-ratn-aO" clipPathUnits="userSpaceOnUse">
        <path d="M0 0h1224v738H0Z" />
      </clipPath>
      <clipPath id="bank-ratn-aP" clipPathUnits="userSpaceOnUse">
        <path d="M1233.1 245.825h.597v-.235h-.597z" />
      </clipPath>
      <clipPath id="bank-ratn-aQ" clipPathUnits="userSpaceOnUse">
        <path d="M1232.978 245.915h.744v-.384h-.744z" />
      </clipPath>
    </defs>
    <g clipPath="url(#bank-ratn-a)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <path
        d="M0 0h31.849L15.925 27.582h-31.849Zm32.024-.1H-.058l-.014.025-16.027 27.759h32.082l.015-.026z"
        style={{
          fill: "#e9e9e6",
          fillOpacity: 1,
          fillRule: "nonzero",
          stroke: "none",
        }}
        transform="translate(628.493 33.347)"
      />
    </g>
    <g clipPath="url(#bank-ratn-b)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <path
        d="M0 0h31.849l15.925 27.582H15.925Zm31.908-.1H-.175l.044.075 15.997 27.709h32.083l-.044-.076z"
        style={{
          fill: "#e9e9e6",
          fillOpacity: 1,
          fillRule: "nonzero",
          stroke: "none",
        }}
        transform="translate(564.62 33.347)"
      />
    </g>
    <g clipPath="url(#bank-ratn-c)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-d)">
        <g clipPath="url(#bank-ratn-e)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GKAAAKDkD1q2NdoMAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1227.338 523.572)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-f)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-g)">
        <g clipPath="url(#bank-ratn-h)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GKAAAKDkD1q2NdoMAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1229.138 523.572)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-i)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-j)">
        <g clipPath="url(#bank-ratn-k)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PL5038GKAAAKGYD2urjsDYAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1234.058 523.572)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-l)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-m)">
        <g clipPath="url(#bank-ratn-n)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABZJREFUCJlj/PDh439mFiaG///+MQAAMT0G1uzySxUAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1224.818 523.691)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-o)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-p)">
        <g clipPath="url(#bank-ratn-q)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GJAAAN5ED1rU8V+YAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.98406 0 0 .384 1234.538 523.691)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-r)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-s)">
        <g clipPath="url(#bank-ratn-t)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GJAAAN5ED1rU8V+YAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86403 0 0 .384 1229.738 523.931)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-u)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-v)">
        <g clipPath="url(#bank-ratn-w)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GJAAAN5ED1rU8V+YAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.98406 0 0 .384 1232.738 523.931)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-x)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-y)">
        <g clipPath="url(#bank-ratn-z)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAABCAYAAAAW/mTzAAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GNAAARukD1luDNTkAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(1.22404 0 0 .384 1236.578 524.051)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-A)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-B)">
        <g clipPath="url(#bank-ratn-C)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PTp438GKAAAKDkD1q2NdoMAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .38398 1236.578 524.291)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-D)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-E)">
        <g clipPath="url(#bank-ratn-F)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABVJREFUCJlj/PHj+38GBgYGRiYmBgApDQPtjdzypgAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1234.058 537.851)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-G)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-H)">
        <g clipPath="url(#bank-ratn-I)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAABCAYAAAAMwoR9AAAABHNCSVQICAgIfAhkiAAAAB1JREFUCJlj/PHj+39GJiYGZPD/3z8GmNj/f/8YAL03Cejh3S38AAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(1.94407 0 0 .384 1235.858 537.851)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-J)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-K)">
        <g clipPath="url(#bank-ratn-L)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/Pnr538GKAAAKTUD7WIIGfMAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1230.938 537.971)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-M)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-N)">
        <g clipPath="url(#bank-ratn-O)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAABCAYAAADn9T9+AAAABHNCSVQICAgIfAhkiAAAACxJREFUCJkFwYENABAMRcHXItT+40k6SMl3Z5lHAFXFaJ25FhEbcwfg3UISHwk7DMEkYYwuAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(2.06404 0 0 .384 1226.618 538.211)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-P)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-Q)">
        <g clipPath="url(#bank-ratn-R)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABpJREFUCJljfPDg/n92NlYGBgYGhh/fvzMAAD3iBphT4kwiAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86403 0 0 .384 1229.738 538.211)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-S)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-T)">
        <g clipPath="url(#bank-ratn-U)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABNJREFUCJlj/PX71/////8zwAAAWfUG7bh+6ScAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86403 0 0 .384 1231.538 538.211)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-V)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-W)">
        <g clipPath="url(#bank-ratn-X)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PHj+38GKAAAKP8D6Le7b1IAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1233.458 538.211)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-Y)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-Z)">
        <g clipPath="url(#bank-ratn-aa)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABVJREFUCJljfPDg3n92Ng4GRiZGBgAmewO4ui2tbAAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1225.058 233.051)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-ab)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-ac)">
        <g clipPath="url(#bank-ratn-ad)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABpJREFUCJlj/Prt2/////8xMDAwMDAzMTEAAFkuBuXURRGiAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86403 0 0 .384 1227.458 233.051)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-ae)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-af)">
        <g clipPath="url(#bank-ratn-ag)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABpJREFUCJlj/PX71/9/f/8yMDEzMzAwMDAAAFn2BvDtV77LAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86403 0 0 .384 1229.258 233.171)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-ah)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-ai)">
        <g clipPath="url(#bank-ratn-aj)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABZJREFUCJljfPf23X9mFhaGf//+MgAAMOwGzpXLSvMAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1226.858 233.411)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-ak)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-al)">
        <g clipPath="url(#bank-ratn-am)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAABCAYAAAAIN1RAAAAABHNCSVQICAgIfAhkiAAAACNJREFUCJldwcEBACAMArFz/4mLUPybnNGUzyZIwte0xTEAD4SmErjbCtoZAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(2.18403 0 0 .384 1229.258 233.411)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-an)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-ao)">
        <g clipPath="url(#bank-ratn-ap)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAABCAYAAADaZ14YAAAABHNCSVQICAgIfAhkiAAAADlJREFUCJmNwcENgCAQRcG3n81egET7L4xoKRhZDzTgjF33yOKF9S6eOYkI+nFSa8MkXAJAGFvyxwc/Ngrue3udrgAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(4.22404 0 0 .384 1233.578 233.411)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aq)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-ar)">
        <g clipPath="url(#bank-ratn-as)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABlJREFUCJljvHnzxn9mRgYGfn4hBm5+fgYANR8D6K4xAfEAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.98406 0 0 .384 1234.058 233.531)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-at)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-au)">
        <g clipPath="url(#bank-ratn-av)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAABCAYAAAC/iqxnAAAABHNCSVQICAgIfAhkiAAAAEVJREFUCJmNi8ENgDAMxJxDgErZf79KjNFceNABsOSfHeMZ5Uxsk3NSVUTEp4KciSQAbGMn0kbrnbNd3PsBsHqtV4SCP7xZfxjuhD4TZwAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(6.024 0 0 .384 1231.778 233.771)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aw)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-ax)">
        <g clipPath="url(#bank-ratn-ay)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAABCAYAAAAW/mTzAAAABHNCSVQICAgIfAhkiAAAABBJREFUCJlj/PHj+38GNAAASD8D6L1M+KsAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(1.22402 0 0 .384 1236.578 233.891)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-az)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aA)">
        <g clipPath="url(#bank-ratn-aB)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAABHNCSVQICAgIfAhkiAAAABFJREFUCJljvHXzxn9mFmYGABb6A5YvclP6AAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .62399 1236.098 244.572)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aC)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aD)">
        <g clipPath="url(#bank-ratn-aE)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAABCAYAAAD9yd/wAAAABHNCSVQICAgIfAhkiAAAACBJREFUCJkFwQENADAIA7Au+PdG0EP428z0g9uVBKTKB3orBnWAuSNHAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(1.22405 0 0 .38398 1228.178 244.811)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aF)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aG)">
        <g clipPath="url(#bank-ratn-aH)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAABCAYAAADeko4lAAAABHNCSVQICAgIfAhkiAAAADxJREFUCJk1ycENwDAIxVADX2333y0ZJgSRS+rbk23O0e6GmfNXVXQ3dh0SUpCZ5Fo873dPU7vwcBQiJA5wExOdHTKYUgAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(3.86402 0 0 .38398 1230.458 244.811)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aI)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aJ)">
        <g clipPath="url(#bank-ratn-aK)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAABHNCSVQICAgIfAhkiAAAABpJREFUCJljvHz54v8/v34x/Pv3j4GFhYUBAGdcCW5bgOlLAAAAAElFTkSuQmCC"
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.86398 0 0 .384 1235.378 244.931)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aL)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aM)">
        <g clipPath="url(#bank-ratn-aN)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABVJREFUCJljvHDuzH8GBgYGRkZGBgAjrANuzHyHCAAAAABJRU5ErkJggg=="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .38398 1228.658 245.171)"
          />
        </g>
      </g>
    </g>
    <g clipPath="url(#bank-ratn-aO)" transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)">
      <g clipPath="url(#bank-ratn-aP)">
        <g clipPath="url(#bank-ratn-aQ)">
          <image
            xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAABCAYAAAAb4BS0AAAABHNCSVQICAgIfAhkiAAAABZJREFUCJljvHP71v+fP38wMDAwMAAAObUGfNvhazYAAAAASUVORK5CYII="
            width={1}
            height={1}
            preserveAspectRatio="none"
            style={{
              imageRendering: "auto",
            }}
            transform="matrix(.74402 0 0 .384 1232.978 245.531)"
          />
        </g>
      </g>
    </g>
    <path
      d="M12.923 44.583v13.734H2.11V25.835c0 7.996 4.354 15.013 10.813 18.748m12.184 2.859V36.579c5.341-.665 9.484-5.216 9.484-10.731 0-5.997-4.842-10.842-10.832-10.842-5.971 0-10.824 4.845-10.824 10.842h-.012V7.088a21.66 21.66 0 0 1 10.836-2.915c11.959 0 21.65 9.693 21.65 21.662 0 11.498-8.972 20.916-20.302 21.607"
      style={{
        fill: "#21317d",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 1,
      }}
      transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)"
    />
    <path
      d="M12.923 44.583C6.464 40.848 2.11 33.83 2.11 25.835V1.486h10.813v24.362h.012c0 5.515 4.131 10.065 9.474 10.73v10.864a21.4 21.4 0 0 1-9.486-2.86"
      style={{
        fill: "#ed1c24",
        fillOpacity: 1,
        fillRule: "nonzero",
        stroke: "none",
        strokeWidth: 1,
      }}
      transform="matrix(1.33333 0 0 -1.33333 -2.813 77.756)"
    />
  </svg>
));
RatnBankLogo.displayName = "RatnBankLogo";
