import { forwardRef, type SVGProps } from "react";
/** UCO Bank: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const UcbaBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 30.276 30.595"
    width="1em"
    height="1em"
    role="img"
    aria-label="UCO Bank"
    ref={ref}
    {...props}
  >
    <defs>
      <clipPath id="bank-ucba-b">
        <path d="M279.485 660.36h24.93V635.4h-24.93z" />
      </clipPath>
      <clipPath id="bank-ucba-a">
        <path d="M279.485 660.36h24.93V635.4h-24.93z" />
      </clipPath>
    </defs>
    <path
      d="M67.662 1022.61s0-.09-.09-.09l-.09.09c0 .09.09.09.09.09.09 0 .09 0 .09-.09"
      style={{
        fill: "#04a",
        fillOpacity: 1,
        fillRule: "evenodd",
        stroke: "none",
      }}
      transform="translate(-82.646 -1012.206)"
    />
    <path
      d="m107.782 1042.705 5.044-5.05v-20.17l-5.072-5.183H87.822l-5.08 5.219v20.17l5.008 5.014z"
      style={{
        fill: "#fff",
        fillOpacity: 1,
        fillRule: "evenodd",
        stroke: "none",
      }}
      transform="translate(-82.646 -1012.206)"
    />
    <g clipPath="url(#bank-ucba-a)" transform="matrix(1.25 0 0 -1.25 -349.554 824.88)">
      <path
        d="m299.752 635.505 4.035 4.039v16.136l-4.058 4.147h-15.945l-4.064-4.175v-16.136l4.006-4.011z"
        style={{
          fill: "none",
          stroke: "#fff",
          strokeWidth: 0.154,
          strokeLinecap: "butt",
          strokeLinejoin: "miter",
          strokeMiterlimit: 2.613,
          strokeDasharray: "none",
          strokeOpacity: 1,
        }}
      />
    </g>
    <path
      d="M107.754 1037.592h-4.944v-5.565l4.216-4.401-8.616-9.359v2.36l5.481 6.421-5.442 5.592v10.065h9.333l5.044-5.05v-20.17l-5.072-5.183H87.822l-5.08 5.219v20.17l5.008 5.014h9.409l-.002-10.065-5.443-5.592 5.481-6.421v-2.36l-8.616 9.359 4.215 4.401v5.565h-4.945v-20.177h19.87zm-13.825-10.883a3.857 3.857 0 0 1 3.855-3.86 3.856 3.856 0 0 1 3.855 3.86 3.857 3.857 0 0 1-3.855 3.86 3.86 3.86 0 0 1-3.855-3.86"
      style={{
        fill: "#000",
        fillOpacity: 1,
        fillRule: "evenodd",
        stroke: "none",
      }}
      transform="translate(-82.646 -1012.206)"
    />
    <g
      clipPath="url(#bank-ucba-b)"
      style={{
        fill: "#04a",
      }}
      transform="matrix(1.25 0 0 -1.25 -349.554 824.88)"
    >
      <path
        d="M299.729 639.595h-3.955v4.452l3.373 3.521-6.893 7.487v-1.888l4.385-5.137-4.354-4.473v-8.052h7.467l4.035 4.039v16.136l-4.058 4.147h-15.945l-4.064-4.175v-16.136l4.006-4.011h7.527l-.002 8.052-4.354 4.473 4.385 5.137v1.888l-6.893-7.487 3.372-3.521v-4.452h-3.956v16.142h15.896zm-11.06 8.706a3.085 3.085 0 1 0 6.168 0 3.086 3.086 0 0 0-3.084-3.088 3.086 3.086 0 0 0-3.084 3.088z"
        style={{
          fill: "#04a",
          stroke: "#000",
          strokeWidth: 0.154,
          strokeLinecap: "butt",
          strokeLinejoin: "miter",
          strokeMiterlimit: 2.613,
          strokeDasharray: "none",
          strokeOpacity: 1,
        }}
      />
    </g>
  </svg>
));
UcbaBankLogo.displayName = "UcbaBankLogo";
