import { forwardRef, type SVGProps } from "react";
/** Axis Bank: its symbol from the indian-banks repository. GENERATED by
 * scripts/generate-bank-logos.mjs; edit that, not this file. */
export const UtibBankLogo = forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 81.629 70.753"
    width="1em"
    height="1em"
    role="img"
    aria-label="Axis Bank"
    ref={ref}
    {...props}
  >
    <defs>
      <clipPath id="bank-utib-a">
        <path d="M27 27h1353.599v939.6H27Z" />
      </clipPath>
    </defs>
    <g
      clipPath="url(#bank-utib-a)"
      style={{
        fill: "#00f",
      }}
      transform="matrix(1.25 0 0 -1.25 -108.521 230.868)"
    >
      <g
        style={{
          fill: "maroon",
        }}
      >
        <path
          d="M0 0h-20.312l-12.333 21.507h20.309z"
          style={{
            fill: "maroon",
            fillOpacity: 1,
            fillRule: "nonzero",
            stroke: "none",
          }}
          transform="translate(152.12 128.092)"
        />
      </g>
      <g
        style={{
          fill: "maroon",
        }}
      >
        <path
          d="m0 0 10.185-17.516-22.498-39.086h-20.273Z"
          style={{
            fill: "maroon",
            fillOpacity: 1,
            fillRule: "nonzero",
            stroke: "none",
          }}
          transform="translate(119.403 184.694)"
        />
      </g>
    </g>
  </svg>
));
UtibBankLogo.displayName = "UtibBankLogo";
