import type { PaTransaction } from "@/features/dashboard/transactions/types";

// TODO(integration): dev-only fallback. paTxnSearchApi is the real endpoint
// (see PaTransactionTable), this array only renders when that call comes
// back with zero rows (e.g. a dev/test MID with no seeded transactions), so
// the table isn't just a blank "No transactions yet" state while building
// against it. Delete this file once every environment has real data to
// query. Every card number below is masked (last 4 digits only); no real
// PAN, email or phone data is used.
//
// Unified Transaction ID & Financial Event Logic: a refund/dispute/
// settlement is NEVER its own row here, it's an entry in the relevant
// transaction's own refunds[]/disputes[]/settlements[] array (see
// PaTransaction's own doc comment). getDisplayStatus/getDisplayStatusBucket
// (paColumns.tsx) derive what the table actually shows from these arrays,
// externalStatus alone is only the underlying payment's own status.

export const MOCK_PA_TRANSACTIONS: PaTransaction[] = [
  // A: Normal, settled, nothing else has happened to it.
  {
    gid: "gl_o-a1f114aebb83002dcmf0L2hX2",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX4242",
    txnCurrency: "INR",
    totalAmount: "14330.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "arjun.mehta@example.com",
    formattedCreationDateTime: "07/08/2026, 09:12:41",
    firstName: "Arjun",
    lastName: "Mehta",
    settlements: [
      {
        id: "gl_o-a1f114aebb83002dcmf0L2hX2-settlement-1",
        transactionId: "gl_o-a1f114aebb83002dcmf0L2hX2",
        amount: 14330,
        currency: "INR",
        status: "SETTLED",
        settledOnDate: "08/08/2026, 09:12:41",
        utrNumber: "UTR140330",
        settledToAccount: "HDFC ****4521",
        settlementReportId: "stl_a1b2c3d4",
      },
    ],
  },
  {
    gid: "gl_o-c3d336cgdd05224feoh2N4jZ4",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    txnCurrency: "INR",
    totalAmount: "8999.50",
    paymentInstrument: "NETBANKING",
    encEmailId: "rohit.sharma@example.com",
    formattedCreationDateTime: "06/08/2026, 19:03:22",
    firstName: "Rohit",
    lastName: "Sharma",
  },

  // B: Partial refund, a single refund event for less than the original amount.
  {
    gid: "gl_o-e5f558eiffh27446gqj4P6lb6",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    txnCurrency: "INR",
    totalAmount: "5000.00",
    paymentInstrument: "UPI",
    encEmailId: "vikram.rao@example.com",
    formattedCreationDateTime: "06/08/2026, 11:58:14",
    firstName: "Vikram",
    lastName: "Rao",
    refunds: [
      {
        id: "gl_o-e5f558eiffh27446gqj4P6lb6-refund-1",
        transactionId: "gl_o-e5f558eiffh27446gqj4P6lb6",
        amount: 1250,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "07/08/2026, 11:58:14",
      },
    ],
  },

  // C: Multiple partial refunds, still not fully refunded.
  {
    gid: "gl_o-j0k003jnkkm72991lvo9U1qg1",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    txnCurrency: "INR",
    totalAmount: "3000.00",
    paymentInstrument: "UPI",
    encEmailId: "meera.joshi@example.com",
    formattedCreationDateTime: "04/08/2026, 14:52:27",
    firstName: "Meera",
    lastName: "Joshi",
    refunds: [
      {
        id: "gl_o-j0k003jnkkm72991lvo9U1qg1-refund-1",
        transactionId: "gl_o-j0k003jnkkm72991lvo9U1qg1",
        amount: 1000,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "duplicate charge",
        createdAt: "05/08/2026, 10:00:00",
      },
      {
        id: "gl_o-j0k003jnkkm72991lvo9U1qg1-refund-2",
        transactionId: "gl_o-j0k003jnkkm72991lvo9U1qg1",
        amount: 899,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "06/08/2026, 09:30:00",
      },
    ],
  },

  // D: Fully refunded, reached via two partial refunds.
  {
    gid: "gl_o-k1l114kollo83002mwp0V2rh2",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX1187",
    txnCurrency: "INR",
    totalAmount: "10000.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "aditya.singh@example.com",
    formattedCreationDateTime: "03/08/2026, 10:21:59",
    firstName: "Aditya",
    lastName: "Singh",
    refunds: [
      {
        id: "gl_o-k1l114kollo83002mwp0V2rh2-refund-1",
        transactionId: "gl_o-k1l114kollo83002mwp0V2rh2",
        amount: 4000,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "product not received",
        createdAt: "04/08/2026, 09:00:00",
      },
      {
        id: "gl_o-k1l114kollo83002mwp0V2rh2-refund-2",
        transactionId: "gl_o-k1l114kollo83002mwp0V2rh2",
        amount: 6000,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "product not received",
        createdAt: "05/08/2026, 09:00:00",
      },
    ],
  },

  // E: Active dispute for the full original amount, no refund.
  {
    gid: "gl_o-m3n336mqqnq05224oyr2X4tj4",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX4821",
    txnCurrency: "INR",
    totalAmount: "12500.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "aditi.rao@example.com",
    formattedCreationDateTime: "08/08/2026, 10:22:15",
    firstName: "Aditi",
    lastName: "Rao",
    disputes: [
      {
        id: "gl_o-m3n336mqqnq05224oyr2X4tj4-dispute-1",
        transactionId: "gl_o-m3n336mqqnq05224oyr2X4tj4",
        amount: 12500,
        currency: "INR",
        reason: "Fraudulent",
        reasonCode: "10.4",
        description: "The cardholder claims they did not authorise this purchase.",
        status: "DISPUTED",
        raisedOn: "10/08/2026, 10:22:15",
        respondBy: "16/08/2026, 10:22:15",
      },
    ],
  },

  // F: Partial dispute, less than the original amount, no refund.
  {
    gid: "gl_o-o5p558osssq27446qat4Z6vl6",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX5310",
    txnCurrency: "INR",
    totalAmount: "8990.00",
    cardBrand: "RUPAY",
    paymentInstrument: "CARDS",
    encEmailId: "priya.menon@example.com",
    formattedCreationDateTime: "08/08/2026, 08:05:52",
    firstName: "Priya",
    lastName: "Menon",
    disputes: [
      {
        id: "gl_o-o5p558osssq27446qat4Z6vl6-dispute-1",
        transactionId: "gl_o-o5p558osssq27446qat4Z6vl6",
        amount: 4000,
        currency: "INR",
        reason: "Product not received",
        reasonCode: "13.1",
        description: "The cardholder claims they did not receive the goods or services purchased.",
        status: "NEEDS_ACTION",
        raisedOn: "10/08/2026, 08:05:52",
        respondBy: "16/08/2026, 08:05:52",
      },
    ],
  },

  // G: Settled, then later partially refunded. The settlement stays exactly
  // as it was, the refund is a separate, subsequent event.
  {
    gid: "gl_o-g7settle01refund1",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX3312",
    txnCurrency: "INR",
    totalAmount: "10000.00",
    cardBrand: "RUPAY",
    paymentInstrument: "CARDS",
    encEmailId: "neha.kulkarni@example.com",
    formattedCreationDateTime: "01/08/2026, 12:00:00",
    firstName: "Neha",
    lastName: "Kulkarni",
    settlements: [
      {
        id: "gl_o-g7settle01refund1-settlement-1",
        transactionId: "gl_o-g7settle01refund1",
        amount: 10000,
        currency: "INR",
        status: "SETTLED",
        settledOnDate: "02/08/2026, 12:00:00",
        utrNumber: "UTR100000",
        settledToAccount: "ICICI ****7789",
        settlementReportId: "stl_a1b2c3d4",
      },
    ],
    refunds: [
      {
        id: "gl_o-g7settle01refund1-refund-1",
        transactionId: "gl_o-g7settle01refund1",
        amount: 2500,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "05/08/2026, 12:00:00",
      },
    ],
  },

  // H: Settled, then partially refunded, then also disputed. All three
  // amounts (settled/refunded/disputed) are tracked independently.
  {
    gid: "gl_o-h8settle01refund1dispute1",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX9021",
    txnCurrency: "INR",
    totalAmount: "10000.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "farhan.ali@example.com",
    formattedCreationDateTime: "01/08/2026, 20:33:11",
    firstName: "Farhan",
    lastName: "Ali",
    settlements: [
      {
        id: "gl_o-h8settle01refund1dispute1-settlement-1",
        transactionId: "gl_o-h8settle01refund1dispute1",
        amount: 10000,
        currency: "INR",
        status: "SETTLED",
        settledOnDate: "02/08/2026, 20:33:11",
        utrNumber: "UTR100001",
        settledToAccount: "Axis ****3312",
        settlementReportId: "stl_a1b2c3d4",
      },
    ],
    refunds: [
      {
        id: "gl_o-h8settle01refund1dispute1-refund-1",
        transactionId: "gl_o-h8settle01refund1dispute1",
        amount: 2500,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "05/08/2026, 09:00:00",
      },
    ],
    disputes: [
      {
        id: "gl_o-h8settle01refund1dispute1-dispute-1",
        transactionId: "gl_o-h8settle01refund1dispute1",
        amount: 2000,
        currency: "INR",
        reason: "Fraudulent",
        reasonCode: "10.4",
        description: "The cardholder claims they did not authorise this purchase.",
        status: "DISPUTED",
        raisedOn: "08/08/2026, 09:00:00",
        respondBy: "14/08/2026, 09:00:00",
      },
    ],
  },

  // I: Multiple partial refunds plus an active dispute, all independent of
  // each other.
  {
    gid: "gl_o-i9refund2dispute1",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX2290",
    txnCurrency: "INR",
    totalAmount: "20000.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "karan.shah@example.com",
    formattedCreationDateTime: "01/08/2026, 15:12:09",
    firstName: "Karan",
    lastName: "Shah",
    refunds: [
      {
        id: "gl_o-i9refund2dispute1-refund-1",
        transactionId: "gl_o-i9refund2dispute1",
        amount: 5000,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "03/08/2026, 09:00:00",
      },
      {
        id: "gl_o-i9refund2dispute1-refund-2",
        transactionId: "gl_o-i9refund2dispute1",
        amount: 3000,
        currency: "INR",
        status: "SUCCEEDED",
        reason: "requested by customer",
        createdAt: "05/08/2026, 09:00:00",
      },
    ],
    disputes: [
      {
        id: "gl_o-i9refund2dispute1-dispute-1",
        transactionId: "gl_o-i9refund2dispute1",
        amount: 4000,
        currency: "INR",
        reason: "Duplicate processing",
        reasonCode: "12.6",
        description: "The cardholder was charged more than once for the same purchase.",
        status: "DISPUTED",
        raisedOn: "09/08/2026, 09:00:00",
        respondBy: "15/08/2026, 09:00:00",
      },
    ],
  },

  // Dispute won, resolved in the merchant's favour, no funds moved.
  {
    gid: "gl_o-n4o447nrrrr16335pzs3Y5uk5",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX9981",
    txnCurrency: "USD",
    totalAmount: "340.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "marcus.lee@example.com",
    formattedCreationDateTime: "08/08/2026, 09:47:33",
    firstName: "Marcus",
    lastName: "Lee",
    disputes: [
      {
        id: "gl_o-n4o447nrrrr16335pzs3Y5uk5-dispute-1",
        transactionId: "gl_o-n4o447nrrrr16335pzs3Y5uk5",
        amount: 340,
        currency: "USD",
        reason: "Duplicate processing",
        reasonCode: "12.6",
        description: "The cardholder was charged more than once for the same purchase.",
        status: "WON",
        raisedOn: "09/08/2026, 09:47:33",
        respondBy: "15/08/2026, 09:47:33",
        resolvedOn: "15/08/2026, 09:47:33",
      },
    ],
  },

  // Dispute lost, resolved against the merchant, funds left via the card
  // network (a chargeback, not a merchant-issued refund, see FUNDS_WITHDRAWN
  // in generateTimelineEvents).
  {
    gid: "gl_o-p6q669pttts38557rbu5A7wm7",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX7726",
    txnCurrency: "EUR",
    totalAmount: "212.50",
    cardBrand: "AMEX",
    paymentInstrument: "CARDS",
    encEmailId: "james.oconnor@example.com",
    formattedCreationDateTime: "07/08/2026, 22:33:41",
    firstName: "James",
    lastName: "O'Connor",
    disputes: [
      {
        id: "gl_o-p6q669pttts38557rbu5A7wm7-dispute-1",
        transactionId: "gl_o-p6q669pttts38557rbu5A7wm7",
        amount: 212.5,
        currency: "EUR",
        reason: "Credit not processed",
        reasonCode: "13.6",
        description: "The cardholder claims a refund or credit was not issued as expected.",
        status: "LOST",
        raisedOn: "09/08/2026, 22:33:41",
        respondBy: "15/08/2026, 22:33:41",
        resolvedOn: "15/08/2026, 22:33:41",
      },
    ],
  },

  // Evidence submitted and forwarded to the issuing bank, PayGlocal's own
  // review already complete (reviewPhase), see deriveDisputeOnlyTimelineSteps.
  {
    gid: "gl_o-q7r770quuuv49668scv6B8xn8",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX4457",
    txnCurrency: "INR",
    totalAmount: "6200.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "rahul.verma@example.com",
    formattedCreationDateTime: "05/08/2026, 11:15:00",
    firstName: "Rahul",
    lastName: "Verma",
    disputes: [
      {
        id: "gl_o-q7r770quuuv49668scv6B8xn8-dispute-1",
        transactionId: "gl_o-q7r770quuuv49668scv6B8xn8",
        amount: 6200,
        currency: "INR",
        reason: "Fraudulent",
        reasonCode: "10.4",
        description: "The cardholder claims they did not authorise this purchase.",
        status: "UNDER_REVIEW",
        raisedOn: "06/08/2026, 11:15:00",
        respondBy: "12/08/2026, 11:15:00",
        documents: ["order-invoice.pdf", "authorization-log.pdf"],
        evidenceSubmittedOn: "08/08/2026, 09:00:00",
        reviewPhase: "BANK_REVIEW",
      },
    ],
  },

  // PayGlocal's review found the submitted evidence inadequate, the
  // merchant needs to upload more before this can move forward.
  {
    gid: "gl_o-r8s881rvvvw50779tdw7C9yo9",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX6689",
    txnCurrency: "INR",
    totalAmount: "3150.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "divya.pillai@example.com",
    formattedCreationDateTime: "04/08/2026, 16:40:00",
    firstName: "Divya",
    lastName: "Pillai",
    disputes: [
      {
        id: "gl_o-r8s881rvvvw50779tdw7C9yo9-dispute-1",
        transactionId: "gl_o-r8s881rvvvw50779tdw7C9yo9",
        amount: 3150,
        currency: "INR",
        reason: "Product not received",
        reasonCode: "13.1",
        description: "The cardholder claims they did not receive the goods or services purchased.",
        status: "INSUFFICIENT_DOCUMENTS",
        raisedOn: "05/08/2026, 16:40:00",
        respondBy: "11/08/2026, 16:40:00",
        documents: ["order-confirmation.pdf"],
        evidenceSubmittedOn: "07/08/2026, 10:00:00",
      },
    ],
  },

  // Plain payment-status rows, unaffected by any of the above.
  {
    gid: "gl_o-b2c225bfcc94113edng1M3iY3",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SENT_FOR_CAPTURE",
    txnCurrency: "INR",
    totalAmount: "3233.00",
    paymentInstrument: "UPI",
    encEmailId: "priya.nair@example.com",
    formattedCreationDateTime: "07/08/2026, 08:47:05",
    firstName: "Priya",
    lastName: "Nair",
  },
  {
    gid: "gl_o-d4e447dheeg16335fpi3O5ka5",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "ISSUER_DECLINE",
    maskedCardNumber: "XXXXXXXXXXXX7789",
    txnCurrency: "INR",
    totalAmount: "5400.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "sneha.kapoor@example.com",
    formattedCreationDateTime: "06/08/2026, 15:26:58",
    firstName: "Sneha",
    lastName: "Kapoor",
    message: "Card declined by issuing bank",
  },
  {
    gid: "gl_o-f6g669fjggi38557hrk5Q7mc7",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "INPROGRESS",
    maskedCardNumber: "XXXXXXXXXXXX3312",
    txnCurrency: "INR",
    totalAmount: "2100.00",
    cardBrand: "RUPAY",
    paymentInstrument: "CARDS",
    encEmailId: "ananya.iyer@example.com",
    formattedCreationDateTime: "05/08/2026, 21:40:37",
    firstName: "Ananya",
    lastName: "Iyer",
  },
  {
    gid: "gl_o-l2m225lppmp94113nxq1W3si3",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SENT_FOR_CAPTURE",
    txnCurrency: "INR",
    totalAmount: "4560.75",
    paymentInstrument: "NETBANKING",
    encEmailId: "ishita.bose@example.com",
    formattedCreationDateTime: "03/08/2026, 08:09:16",
    firstName: "Ishita",
    lastName: "Bose",
  },
];
