import type { TeamMemberRow } from "@/features/dashboard/team-management/types";

// TODO(integration): mock data only, wire up to the real team/user-management
// endpoints per the CLAUDE.md migration checklist before shipping, endpoint
// URL, request payload and response statuses must all be copied from
// pg-dashboard, not guessed.

// Every member below belongs to the same merchant account, team management
// lists the people who can log into *this* merchant's dashboard, not one
// MID per person.
export const TEAM_MERCHANT_ID = "700010045821";
const MERCHANT_ID = TEAM_MERCHANT_ID;

export const teamMemberRows: TeamMemberRow[] = [
  {
    id: "usr_a1b2c3",
    firstName: "Aditi",
    lastName: "Rao",
    username: "aditi.rao",
    role: "ADMIN",
    merchantId: MERCHANT_ID,
    status: "ACTIVE",
    phoneCountryCode: "+91",
    phone: "9820011223",
    email: "aditi.rao@merchant.com",
    whatsappEchoEnabled: true,
    invitedAt: "2026-01-12T09:30:00.000Z",
  },
  {
    id: "usr_d4e5f6",
    firstName: "Karan",
    lastName: "Mehta",
    username: "karan.mehta",
    role: "ADMIN",
    merchantId: MERCHANT_ID,
    status: "ACTIVE",
    phoneCountryCode: "+91",
    phone: "9845566778",
    email: "karan.mehta@merchant.com",
    whatsappEchoEnabled: false,
    invitedAt: "2026-02-03T11:05:00.000Z",
  },
  {
    id: "usr_g7h8i9",
    firstName: "Sneha",
    lastName: "Iyer",
    username: "sneha.iyer",
    role: "VIEW_ONLY",
    merchantId: MERCHANT_ID,
    status: "ACTIVE",
    phoneCountryCode: "+91",
    phone: "9900112233",
    email: "sneha.iyer@merchant.com",
    whatsappEchoEnabled: true,
    invitedAt: "2026-02-18T14:40:00.000Z",
  },
  {
    id: "usr_j1k2l3",
    firstName: "Rohit",
    lastName: "Verma",
    username: "rohit.verma",
    role: "VIEW_ONLY",
    merchantId: MERCHANT_ID,
    status: "ACTIVE",
    phoneCountryCode: "+91",
    phone: "9765432109",
    email: "rohit.verma@merchant.com",
    whatsappEchoEnabled: false,
    invitedAt: "2026-03-01T08:15:00.000Z",
  },
  {
    id: "usr_m4n5o6",
    firstName: "Priya",
    lastName: "Nair",
    username: "priya.nair",
    role: "ADMIN",
    merchantId: MERCHANT_ID,
    status: "INVITE_SENT",
    phoneCountryCode: "+91",
    phone: "9911223344",
    email: "priya.nair@merchant.com",
    whatsappEchoEnabled: false,
    invitedAt: "2026-03-14T16:20:00.000Z",
  },
  {
    id: "usr_p7q8r9",
    firstName: "Farhan",
    lastName: "Sheikh",
    username: "farhan.sheikh",
    role: "VIEW_ONLY",
    merchantId: MERCHANT_ID,
    status: "INVITE_SENT",
    phoneCountryCode: "+91",
    phone: "9822334455",
    email: "farhan.sheikh@merchant.com",
    whatsappEchoEnabled: true,
    invitedAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "usr_s1t2u3",
    firstName: "Meera",
    lastName: "Pillai",
    username: "meera.pillai",
    role: "VIEW_ONLY",
    merchantId: MERCHANT_ID,
    status: "INACTIVE",
    phoneCountryCode: "+91",
    phone: "9877001122",
    email: "meera.pillai@merchant.com",
    whatsappEchoEnabled: false,
    invitedAt: "2025-11-09T12:50:00.000Z",
  },
  {
    id: "usr_v4w5x6",
    firstName: "Nikhil",
    lastName: "Desai",
    username: "nikhil.desai",
    role: "ADMIN",
    merchantId: MERCHANT_ID,
    status: "ACTIVE",
    phoneCountryCode: "+91",
    phone: "9833445566",
    email: "nikhil.desai@merchant.com",
    whatsappEchoEnabled: true,
    invitedAt: "2025-12-22T07:45:00.000Z",
  },
];
