import type { RelativeRangeValue } from "@/components/common/filters/FilterChips";
import type { BaseResponse } from "@/types/common";

/**
 * One row of the invoice list, from pg-dashboard's McaInvoiceData.
 *
 * Three fields are declared optional here that production's interface omits
 * entirely: `clientName`, `clientBusinessName` and `recurringType`. Its table
 * renders all three via antd `dataIndex`, which reads straight off the response
 * without type-checking, so the interface is simply under-specified rather than
 * the payload lacking them (the detail-level InvoiceData does declare the same
 * names). They are optional here so the columns production has can be rendered
 * without asserting a field this migration cannot verify; absent values show as
 * an em dash.
 */
export interface McaInvoiceRow {
  id: string;
  mid: string;
  clientId: string;
  clientName?: string;
  clientBusinessName?: string;
  currency: string;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string;
  formattedCreationDate: string;
  formattedUpdatedDate: string;
  gid: string | null;
  autoGenerated: boolean | null;
  status: "DRAFT" | "ACTIVE" | "PAID" | "PAID_OUTSIDE" | "OUTSTANDING";
  totalAmount: string;
  type: "DEFAULT" | "RECURRING" | "UPLOADED";
  recurringType?: string;
  source?: "PAYGLOCAL" | "ZOHO";
}

export type McaInvoicesResponse = BaseResponse<{
  data: McaInvoiceRow[];
  totalCount: number;
}>;

/** Counts behind the summary cards. Note the doubly-nested `data`. */
export interface McaInvoiceSummaryData {
  totalNo: number;
  totalCreated: number;
  totalPaid: number;
  totalOutstanding: number;
  totalActive: number;
}

export type McaInvoiceSummaryResponse = BaseResponse<{ data: McaInvoiceSummaryData }>;

/** Filter state the request body is built from. */
export interface InvoiceFilterValues {
  status?: string[];
  /** Set only by the Recurring tab. */
  type?: string[];
  startTime?: number;
  endTime?: number;
}

/**
 * Search body. Mirrors TableReqBody. Note the MID key inside `fieldSearch` is
 * `mid`, not the `merchantId` the transactions search uses.
 */
export interface InvoiceSearchBody {
  pageLimit: number;
  from: number;
  searchFilterType?: string;
  queryString?: string;
  fieldSearch?: Record<string, string | string[]>;
  startTime?: number;
  endTime?: number;
}

/**
 * The minimum an invoice-scoped dialog needs to address and describe an
 * invoice. `McaInvoiceRow` satisfies it structurally, and so does a detail
 * record, which lets the Mark-as-paid and Link-transaction dialogs be shared
 * between the list and the details page without either one depending on the
 * other's fuller shape.
 */
export interface InvoiceRef {
  id: string;
  mid: string;
  invoiceNumber: string;
  currency: string;
  totalAmount: string;
  clientName?: string;
  clientBusinessName?: string;
}

/**
 * The Date filter, as one value.
 *
 * The chip's two modes and the epoch window they resolve to are kept together
 * because they are one filter, not three: exactly one of `range` (absolute
 * yyyy-mm-dd bounds) and `relative` ("last N weeks/days/…") is ever set, and
 * `window` is whichever of them resolved to epoch millis at the moment it was
 * applied. Holding them as one object is what lets the summary's range picker
 * and the table's Date chip be two views of a single piece of state, so
 * changing either one is visible in both.
 */
export interface InvoiceDateFilter {
  range: { from: string; to: string };
  relative: RelativeRangeValue;
  /** Resolved bounds for a relative range, epoch millis. Null when the filter
   *  is absolute (the range is converted at request time) or unset. */
  window: { startTime: number; endTime: number } | null;
}

// ── Upload invoice ──────────────────────────────────────────────────────────

/** Leg 1's response: where to PUT the file, and the id extraction is keyed by. */
export type UploadInvoicePresignResponse = BaseResponse<{
  upload_url: string;
  metaData: {
    invoiceId: string;
    maxSize: string;
    merchantId: string;
    fileExtension: string;
  };
}>;

/**
 * What extraction read off the uploaded PDF.
 *
 * A subset of production's InvoiceData — only the fields its confirm form
 * actually seeds from (UPLOAD_INVOICE_FIELDS). Every one is optional because
 * extraction is best-effort: a field it could not read comes back empty and the
 * merchant types it in, which is the whole point of the confirm step.
 */
export interface ScannedInvoiceExtract {
  invoiceDate?: string | null;
  dueDate?: string | null;
  currency?: string | null;
  totalAmount?: string | number | null;
  invoiceNumber?: string | null;
}

/**
 * Leg 3's response. `data` is null while extraction is still running, which is
 * what the poll waits on.
 *
 * `mcaClientList` is the merchant's existing clients PLUS, when extraction
 * recognised a client that is not on file yet, one entry whose id is prefixed
 * `NEW_`. Picking that one creates the client along with the invoice — see the
 * new-client note in the confirm step.
 */
export type ScannedInvoiceResponse = BaseResponse<{
  extractedData: ScannedInvoiceExtract;
  mcaClientList: { name: string; id: string }[];
} | null>;

/** The body POSTed to add-client-invoice, field for field as pg-dashboard sends it. */
export interface AddClientInvoicePayload {
  clientId: string;
  clientName: string;
  currency: string;
  totalAmount: string;
  /** YYYY-MM-DD. */
  invoiceDate: string;
  /** YYYY-MM-DD. */
  dueDate: string;
  invoiceNumber: string;
  userCreateConsent: boolean;
}
