import type { BaseResponse } from "@/types/common";

/**
 * One row of the invoice list, from pg-dashboard's McaInvoiceData.
 *
 * Three fields are declared optional here that production's interface omits
 * entirely: `clientName`, `clientBusinessName` and `recurringType`. Its table
 * renders all three via antd `dataIndex`, which reads straight off the response
 * without type-checking, so the interface is simply under-specified rather than
 * the payload lacking them (the detail-level InvoiceData does declare the same
 * names). They are optional here so the columns production has can be rendered
 * without asserting a field this migration cannot verify; absent values show as
 * an em dash.
 */
export interface McaInvoiceRow {
  id: string;
  mid: string;
  clientId: string;
  clientName?: string;
  clientBusinessName?: string;
  currency: string;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string;
  formattedCreationDate: string;
  formattedUpdatedDate: string;
  gid: string | null;
  autoGenerated: boolean | null;
  status: "DRAFT" | "ACTIVE" | "PAID" | "PAID_OUTSIDE" | "OUTSTANDING";
  totalAmount: string;
  type: "DEFAULT" | "RECURRING" | "UPLOADED";
  recurringType?: string;
  source?: "PAYGLOCAL" | "ZOHO";
}

export type McaInvoicesResponse = BaseResponse<{
  data: McaInvoiceRow[];
  totalCount: number;
}>;

/** Counts behind the summary cards. Note the doubly-nested `data`. */
export interface McaInvoiceSummaryData {
  totalNo: number;
  totalCreated: number;
  totalPaid: number;
  totalOutstanding: number;
  totalActive: number;
}

export type McaInvoiceSummaryResponse = BaseResponse<{ data: McaInvoiceSummaryData }>;

/** Filter state the request body is built from. */
export interface InvoiceFilterValues {
  status?: string[];
  /** Set only by the Recurring tab. */
  type?: string[];
  startTime?: number;
  endTime?: number;
}

/**
 * Search body. Mirrors TableReqBody. Note the MID key inside `fieldSearch` is
 * `mid`, not the `merchantId` the transactions search uses.
 */
export interface InvoiceSearchBody {
  pageLimit: number;
  from: number;
  searchFilterType?: string;
  queryString?: string;
  fieldSearch?: Record<string, string | string[]>;
  startTime?: number;
  endTime?: number;
}

/**
 * The minimum an invoice-scoped dialog needs to address and describe an
 * invoice. `McaInvoiceRow` satisfies it structurally, and so does a detail
 * record, which lets the Mark-as-paid and Link-transaction dialogs be shared
 * between the list and the details page without either one depending on the
 * other's fuller shape.
 */
export interface InvoiceRef {
  id: string;
  mid: string;
  invoiceNumber: string;
  currency: string;
  totalAmount: string;
  clientName?: string;
  clientBusinessName?: string;
}
