import type { Client } from "@/features/dashboard/client-management/types";

/**
 * Placeholder client book for the Client Management page. There is no client
 * endpoint wired up in v2 yet, so this module stands in for one — the same
 * arrangement as the SKU catalogue (sku-management/mock-data.ts) and the
 * Transactions page's settlement analytics. Wiring the backend up should mean
 * replacing this source with a query returning the same `Client[]` shape, not
 * touching the table.
 *
 * Every field is a literal, never a `Math.random()`/`Date.now()` draw: random
 * or clock-derived values differ between the server and client renders (a
 * hydration mismatch) and change on every re-render, which is exactly what
 * CLAUDE.md's purity rule forbids.
 *
 * The rows deliberately spread across the axes the table has to survive:
 * fourteen countries so the Country filter has something to narrow, five
 * currencies including INR (the one figure that groups in lakhs rather than
 * thousands), outstanding balances from zero to seven figures, business names
 * both short and long enough to test the column's width, and creation dates
 * spanning two years so a date range excludes some rows rather than all or
 * none.
 */
export const MOCK_CLIENTS: Client[] = [
  {
    id: "cli-001",
    businessName: "Northwind Trading Co.",
    primaryContactName: "Amelia Hartley",
    email: "amelia.hartley@northwindtrading.co.uk",
    phoneDialCode: "+44",
    phoneNumber: "7911123456",
    countryIso2: "GB",
    countryName: "United Kingdom",
    outstandingAmount: 48_250.0,
    outstandingCurrency: "GBP",
    createdAt: "2024-11-04T09:20:00Z",
  },
  {
    id: "cli-002",
    businessName: "Meridian Logistics LLC",
    primaryContactName: "Daniel Okafor",
    email: "d.okafor@meridianlogistics.com",
    phoneDialCode: "+1",
    phoneNumber: "4155550142",
    countryIso2: "US",
    countryName: "United States",
    outstandingAmount: 132_890.75,
    outstandingCurrency: "USD",
    createdAt: "2024-08-19T14:05:00Z",
  },
  {
    id: "cli-003",
    businessName: "Kessler Maschinenbau GmbH",
    primaryContactName: "Lena Fischer",
    email: "l.fischer@kessler-maschinenbau.de",
    phoneDialCode: "+49",
    phoneNumber: "15112345678",
    countryIso2: "DE",
    countryName: "Germany",
    outstandingAmount: 0,
    outstandingCurrency: "EUR",
    createdAt: "2025-02-27T11:45:00Z",
  },
  {
    id: "cli-004",
    businessName: "Sanjivani Exports Pvt Ltd",
    primaryContactName: "Rohit Deshmukh",
    email: "rohit.deshmukh@sanjivaniexports.in",
    phoneDialCode: "+91",
    phoneNumber: "9820045611",
    countryIso2: "IN",
    countryName: "India",
    outstandingAmount: 1_247_500.0,
    outstandingCurrency: "INR",
    createdAt: "2024-05-12T06:30:00Z",
  },
  {
    id: "cli-005",
    businessName: "Harbourline Freight Pte Ltd",
    primaryContactName: "Wei Ling Tan",
    email: "weiling.tan@harbourline.sg",
    phoneDialCode: "+65",
    phoneNumber: "81234567",
    countryIso2: "SG",
    countryName: "Singapore",
    outstandingAmount: 22_640.5,
    outstandingCurrency: "SGD",
    createdAt: "2025-06-03T02:10:00Z",
  },
  {
    id: "cli-006",
    businessName: "Bluegum Interiors",
    primaryContactName: "Chloe Barrett",
    email: "chloe@blueguminteriors.com.au",
    phoneDialCode: "+61",
    phoneNumber: "412345678",
    countryIso2: "AU",
    countryName: "Australia",
    outstandingAmount: 9_780.0,
    outstandingCurrency: "AUD",
    createdAt: "2025-01-16T22:40:00Z",
  },
  {
    id: "cli-007",
    businessName: "Al Noor General Trading",
    primaryContactName: "Fatima Al Zaabi",
    email: "fatima.alzaabi@alnoortrading.ae",
    phoneDialCode: "+971",
    phoneNumber: "501234567",
    countryIso2: "AE",
    countryName: "United Arab Emirates",
    outstandingAmount: 386_400.0,
    outstandingCurrency: "AED",
    createdAt: "2024-09-30T08:15:00Z",
  },
  {
    id: "cli-008",
    businessName: "Maple & Birch Studio",
    primaryContactName: "Owen Tremblay",
    email: "owen.tremblay@mapleandbirch.ca",
    phoneDialCode: "+1",
    phoneNumber: "6135550188",
    countryIso2: "CA",
    countryName: "Canada",
    outstandingAmount: 4_115.25,
    outstandingCurrency: "CAD",
    createdAt: "2025-04-08T17:55:00Z",
  },
  {
    id: "cli-009",
    businessName: "Atelier Rousseau SARL",
    primaryContactName: "Camille Rousseau",
    email: "camille@atelier-rousseau.fr",
    phoneDialCode: "+33",
    phoneNumber: "612345678",
    countryIso2: "FR",
    countryName: "France",
    outstandingAmount: 17_960.0,
    outstandingCurrency: "EUR",
    createdAt: "2024-07-22T13:25:00Z",
  },
  {
    id: "cli-010",
    businessName: "Kiyomizu Craft KK",
    primaryContactName: "Haruto Nakamura",
    email: "h.nakamura@kiyomizucraft.jp",
    phoneDialCode: "+81",
    phoneNumber: "9012345678",
    countryIso2: "JP",
    countryName: "Japan",
    outstandingAmount: 0,
    outstandingCurrency: "USD",
    createdAt: "2025-05-29T04:00:00Z",
  },
  {
    id: "cli-011",
    businessName: "Vaalpark Agri Holdings",
    primaryContactName: "Thandiwe Mokoena",
    email: "thandiwe.mokoena@vaalparkagri.co.za",
    phoneDialCode: "+27",
    phoneNumber: "821234567",
    countryIso2: "ZA",
    countryName: "South Africa",
    outstandingAmount: 63_310.0,
    outstandingCurrency: "USD",
    createdAt: "2024-12-11T10:35:00Z",
  },
  {
    id: "cli-012",
    businessName: "Costa Verde Alimentos Ltda",
    primaryContactName: "Beatriz Almeida",
    email: "beatriz.almeida@costaverdealimentos.br",
    phoneDialCode: "+55",
    phoneNumber: "11987654321",
    countryIso2: "BR",
    countryName: "Brazil",
    outstandingAmount: 88_425.6,
    outstandingCurrency: "USD",
    createdAt: "2025-03-19T19:05:00Z",
  },
  {
    id: "cli-013",
    businessName: "Lindqvist Design AB",
    primaryContactName: "Erik Lindqvist",
    email: "erik@lindqvistdesign.se",
    phoneDialCode: "+46",
    phoneNumber: "701234567",
    countryIso2: "SE",
    countryName: "Sweden",
    outstandingAmount: 12_050.0,
    outstandingCurrency: "EUR",
    createdAt: "2025-07-24T07:50:00Z",
  },
  {
    id: "cli-014",
    businessName: "Te Awa Organics",
    primaryContactName: "Māia Rangi",
    email: "maia.rangi@teawaorganics.nz",
    phoneDialCode: "+64",
    phoneNumber: "211234567",
    countryIso2: "NZ",
    countryName: "New Zealand",
    outstandingAmount: 5_690.4,
    outstandingCurrency: "AUD",
    createdAt: "2024-10-07T21:15:00Z",
  },
  {
    id: "cli-015",
    businessName: "Zenith Software Solutions",
    primaryContactName: "Priya Venkatesan",
    email: "priya.v@zenithsoftware.in",
    phoneDialCode: "+91",
    phoneNumber: "9945012388",
    countryIso2: "IN",
    countryName: "India",
    outstandingAmount: 342_800.0,
    outstandingCurrency: "INR",
    createdAt: "2025-08-02T05:45:00Z",
  },
  {
    id: "cli-016",
    businessName: "Pemberton & Hale Advisory",
    primaryContactName: "Julian Hale",
    email: "julian.hale@pembertonhale.co.uk",
    phoneDialCode: "+44",
    phoneNumber: "7700900321",
    countryIso2: "GB",
    countryName: "United Kingdom",
    outstandingAmount: 74_500.0,
    outstandingCurrency: "GBP",
    createdAt: "2024-06-14T15:30:00Z",
  },
  {
    id: "cli-017",
    businessName: "Solaris Renewables Inc.",
    primaryContactName: "Marcus Whitfield",
    email: "m.whitfield@solarisrenewables.com",
    phoneDialCode: "+1",
    phoneNumber: "2125550176",
    countryIso2: "US",
    countryName: "United States",
    outstandingAmount: 918_240.0,
    outstandingCurrency: "USD",
    createdAt: "2025-09-11T12:00:00Z",
  },
  {
    id: "cli-018",
    businessName: "Van Doorn Handelsmaatschappij",
    primaryContactName: "Sanne van Doorn",
    email: "sanne@vandoornhandel.nl",
    phoneDialCode: "+31",
    phoneNumber: "612345678",
    countryIso2: "NL",
    countryName: "Netherlands",
    outstandingAmount: 26_775.9,
    outstandingCurrency: "EUR",
    createdAt: "2025-10-28T09:10:00Z",
  },
];
