/**
 * Centralized icon registry — the ONLY module allowed to import `lucide-react`
 * directly (enforced by the `no-restricted-imports` ESLint rule). Every other
 * file references icons through the <Icon name="..."/> component.
 *
 * Add an icon: import it here and add one kebab-case entry to ICONS.
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Angry,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  BarChart2,
  Bell,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  Clock,
  Copy,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  FileText,
  Frown,
  Gauge,
  Gift,
  GitPullRequest,
  Globe,
  Globe2,
  GripVertical,
  IndianRupee,
  HelpCircle,
  Inbox,
  Info,
  KeyRound,
  Laugh,
  LayoutGrid,
  LineChart,
  Link2,
  Loader2,
  Lock,
  Maximize2,
  Minimize2,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Meh,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  Plus,
  Receipt,
  RefreshCw,
  Repeat2,
  Scale,
  Search,
  SendHorizontal,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  UserPlus,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";
import { NoTransactionsIllustration } from "@/components/icon/NoTransactionsIllustration";

export const ICONS = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  angry: Angry,
  ban: Ban,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  "bar-chart": BarChart2,
  bell: Bell,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-dollar-sign": CircleDollarSign,
  clock: Clock,
  copy: Copy,
  "credit-card": CreditCard,
  database: Database,
  download: Download,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  frown: Frown,
  gauge: Gauge,
  gift: Gift,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "globe-2": Globe2,
  "grip-vertical": GripVertical,
  "help-circle": HelpCircle,
  inbox: Inbox,
  "indian-rupee": IndianRupee,
  info: Info,
  "key-round": KeyRound,
  laugh: Laugh,
  "layout-grid": LayoutGrid,
  "line-chart": LineChart,
  link: Link2,
  loader: Loader2,
  lock: Lock,
  "maximize-2": Maximize2,
  "minimize-2": Minimize2,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  meh: Meh,
  menu: Menu,
  "message-circle": MessageCircle,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "no-transactions-illustration": NoTransactionsIllustration as unknown as LucideIcon,
  package: Package,
  paperclip: Paperclip,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  "pie-chart": PieChart,
  "piggy-bank": PiggyBank,
  plus: Plus,
  receipt: Receipt,
  refresh: RefreshCw,
  repeat: Repeat2,
  scale: Scale,
  search: Search,
  "send-horizontal": SendHorizontal,
  settings: Settings,
  "share-2": Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  square: Square,
  sun: Sun,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  upload: Upload,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
  x: X,

} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export type { LucideProps } from "lucide-react";
