/**
 * Centralized icon registry — the ONLY module allowed to import `lucide-react`
 * directly (enforced by the `no-restricted-imports` ESLint rule). Every other
 * file references icons through the <Icon name="..."/> component.
 *
 * Add an icon: import it here and add one kebab-case entry to ICONS.
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  BarChart2,
  Bell,
  Building2,
  Calculator,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  Clock,
  Copy,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gauge,
  GitPullRequest,
  Globe,
  Globe2,
  GripVertical,
  IndianRupee,
  HelpCircle,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  LineChart,
  Link2,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  Minimize2,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Phone,
  PieChart,
  PiggyBank,
  Plus,
  Receipt,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Send,
  Scale,
  Search,
  SendHorizontal,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Square,
  Sun,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";
import { AmazonLogo } from "@/components/icon/AmazonLogo";
import { DeelLogo } from "@/components/icon/DeelLogo";
import { FreelancerLogo } from "@/components/icon/FreelancerLogo";
import { MdrOfferIcon } from "@/components/icon/MdrOfferIcon";
import { ToptalLogo } from "@/components/icon/ToptalLogo";
import { UpworkLogo } from "@/components/icon/UpworkLogo";

export const ICONS = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  ban: Ban,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  "bar-chart": BarChart2,
  bell: Bell,
  "building-2": Building2,
  calculator: Calculator,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-dollar-sign": CircleDollarSign,
  clock: Clock,
  copy: Copy,
  "credit-card": CreditCard,
  database: Database,
  download: Download,
  // Two-arrow (diagonal, opposing-corners) expand/collapse pair, matching
  // the rest of the product's iconography more closely than the previous
  // four-arrow Expand/Shrink glyphs. Keys unchanged so existing <Icon
  // name="expand"/"shrink"> call sites (drawer Expand, page Collapse) don't
  // need to change, only what they render.
  expand: Maximize2,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  filter: Filter,
  gauge: Gauge,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "globe-2": Globe2,
  "grip-vertical": GripVertical,
  "help-circle": HelpCircle,
  inbox: Inbox,
  "indian-rupee": IndianRupee,
  info: Info,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  "line-chart": LineChart,
  link: Link2,
  loader: Loader2,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  package: Package,
  paperclip: Paperclip,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pencil: Pencil,
  phone: Phone,
  "pie-chart": PieChart,
  "piggy-bank": PiggyBank,
  plus: Plus,
  receipt: Receipt,
  refresh: RefreshCw,
  "rotate-ccw": RotateCcw,
  send: Send,
  repeat: Repeat2,
  scale: Scale,
  search: Search,
  "send-horizontal": SendHorizontal,
  settings: Settings,
  share: Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  shrink: Minimize2,
  smartphone: Smartphone,
  sparkles: Sparkles,
  square: Square,
  sun: Sun,
  timer: Timer,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  upload: Upload,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
  x: X,

  // ─── Platform brand marks (Platforms tutorial page) ────────────────────────
  // Placeholder artwork until the official assets land — see each file's own
  // note. Registered here, like every other SVG in the product, so call sites
  // stay `<Icon name="…" />` and never reference an asset path.
  "amazon-logo": AmazonLogo as unknown as LucideIcon,
  "deel-logo": DeelLogo as unknown as LucideIcon,
  "freelancer-logo": FreelancerLogo as unknown as LucideIcon,
  "mdr-offer": MdrOfferIcon as unknown as LucideIcon,
  "toptal-logo": ToptalLogo as unknown as LucideIcon,
  "upwork-logo": UpworkLogo as unknown as LucideIcon,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export type { LucideProps } from "lucide-react";
