import type { PaTransaction } from "@/features/dashboard/pa-transactions/types";

// TODO(integration): dev-only fallback. paTxnSearchApi is the real endpoint
// (see PaTransactionTable), this array only renders when that call comes
// back with zero rows (e.g. a dev/test MID with no seeded transactions), so
// the table isn't just a blank "No transactions yet" state while building
// against it. Delete this file once every environment has real data to
// query. Every card number below is masked (last 4 digits only); no real
// PAN, email or phone data is used.

export const MOCK_PA_TRANSACTIONS: PaTransaction[] = [
  {
    gid: "gl_o-a1f114aebb83002dcmf0L2hX2",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX4242",
    txnCurrency: "INR",
    totalAmount: "14330.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "arjun.mehta@example.com",
    formattedCreationDateTime: "07/08/2026, 09:12:41",
    firstName: "Arjun",
    lastName: "Mehta",
  },
  {
    gid: "gl_o-b2c225bfcc94113edng1M3iY3",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SENT_FOR_CAPTURE",
    txnCurrency: "INR",
    totalAmount: "3233.00",
    paymentInstrument: "UPI",
    encEmailId: "priya.nair@example.com",
    formattedCreationDateTime: "07/08/2026, 08:47:05",
    firstName: "Priya",
    lastName: "Nair",
  },
  {
    gid: "gl_o-c3d336cgdd05224feoh2N4jZ4",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    txnCurrency: "INR",
    totalAmount: "8999.50",
    paymentInstrument: "NETBANKING",
    encEmailId: "rohit.sharma@example.com",
    formattedCreationDateTime: "06/08/2026, 19:03:22",
    firstName: "Rohit",
    lastName: "Sharma",
  },
  {
    gid: "gl_o-d4e447dheeg16335fpi3O5ka5",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "ISSUER_DECLINE",
    maskedCardNumber: "XXXXXXXXXXXX7789",
    txnCurrency: "INR",
    totalAmount: "5400.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "sneha.kapoor@example.com",
    formattedCreationDateTime: "06/08/2026, 15:26:58",
    firstName: "Sneha",
    lastName: "Kapoor",
    message: "Card declined by issuing bank",
  },
  {
    gid: "gl_o-e5f558eiffh27446gqj4P6lb6",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SENT_FOR_REFUND",
    txnCurrency: "INR",
    totalAmount: "1250.00",
    paymentInstrument: "UPI",
    encEmailId: "vikram.rao@example.com",
    formattedCreationDateTime: "06/08/2026, 11:58:14",
    firstName: "Vikram",
    lastName: "Rao",
  },
  {
    gid: "gl_o-f6g669fjggi38557hrk5Q7mc7",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "INPROGRESS",
    maskedCardNumber: "XXXXXXXXXXXX3312",
    txnCurrency: "INR",
    totalAmount: "2100.00",
    cardBrand: "RUPAY",
    paymentInstrument: "CARDS",
    encEmailId: "ananya.iyer@example.com",
    formattedCreationDateTime: "05/08/2026, 21:40:37",
    firstName: "Ananya",
    lastName: "Iyer",
  },
  {
    gid: "gl_o-g7h770gkhhj49668isl6R8nd8",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX5566",
    txnCurrency: "USD",
    totalAmount: "129.00",
    cardBrand: "AMEX",
    paymentInstrument: "CARDS",
    encEmailId: "daniel.wu@example.com",
    formattedCreationDateTime: "05/08/2026, 17:15:02",
    firstName: "Daniel",
    lastName: "Wu",
  },
  {
    gid: "gl_o-h8i881hliik50779jtm7S9oe9",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    txnCurrency: "INR",
    totalAmount: "6720.00",
    paymentInstrument: "NETBANKING",
    encEmailId: "kavya.reddy@example.com",
    formattedCreationDateTime: "05/08/2026, 12:04:49",
    firstName: "Kavya",
    lastName: "Reddy",
  },
  {
    gid: "gl_o-i9j992imjjl61880kun8T0pf0",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "GENERAL_DECLINE",
    maskedCardNumber: "XXXXXXXXXXXX9021",
    txnCurrency: "INR",
    totalAmount: "3999.00",
    cardBrand: "MASTERCARD",
    paymentInstrument: "CARDS",
    encEmailId: "farhan.ali@example.com",
    formattedCreationDateTime: "04/08/2026, 20:33:11",
    firstName: "Farhan",
    lastName: "Ali",
    message: "Insufficient funds",
  },
  {
    gid: "gl_o-j0k003jnkkm72991lvo9U1qg1",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "REFUND_STARTED",
    txnCurrency: "INR",
    totalAmount: "899.00",
    paymentInstrument: "UPI",
    encEmailId: "meera.joshi@example.com",
    formattedCreationDateTime: "04/08/2026, 14:52:27",
    firstName: "Meera",
    lastName: "Joshi",
  },
  {
    gid: "gl_o-k1l114kollo83002mwp0V2rh2",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SUCCESS",
    maskedCardNumber: "XXXXXXXXXXXX1187",
    txnCurrency: "INR",
    totalAmount: "17650.00",
    cardBrand: "VISA",
    paymentInstrument: "CARDS",
    encEmailId: "aditya.singh@example.com",
    formattedCreationDateTime: "03/08/2026, 10:21:59",
    firstName: "Aditya",
    lastName: "Singh",
  },
  {
    gid: "gl_o-l2m225lppmp94113nxq1W3si3",
    merchantId: "MID-SWIG-GEN-003",
    externalStatus: "SENT_FOR_CAPTURE",
    txnCurrency: "INR",
    totalAmount: "4560.75",
    paymentInstrument: "NETBANKING",
    encEmailId: "ishita.bose@example.com",
    formattedCreationDateTime: "03/08/2026, 08:09:16",
    firstName: "Ishita",
    lastName: "Bose",
  },
];
